<!DOCTYPE HTML>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0"/>
<meta name="apple-mobile-web-app-capable" content="yes"/>
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<title>手机绑定</title>
<link href="/css/swiper.min.css" rel="stylesheet" type="text/css" />
<link href="/css/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div class="phonebox">
	<dl class="phoneTopdl">
		<dt><img src="/images/bg04.png" width="210px" /></dt>
		<dd>绑定手机号，第一时间查看订单详情</dd>
	</dl>
	<div class="phoneform">
		<div class="phonefotop overf">
			<div class="phonefotopdiv overf">
				<span class="phonerightpan fr">60秒后重发</span>
				<div class="phoneputleftdiv">
					<input type="text" class="phonetxt" placeholder="请输入短信验证码" />
				</div>
			</div>
			<p class="phonefotopnote"><?=$this->phone ?></p>
		</div>
		<a href="javascript:;"><span class="phonebtn">绑定</span></a>
	</div>
</div>
<script type="text/javascript" src="/js/jquery-1.9.1.js" ></script>
<script type="text/javascript" src="/js/method.js" ></script>
<script>
	//获取绑定的手机号
// 	var phoneNum = sessionStorage.getItem("phoneNum");
// 	$(".phonefotopnote").html("即将绑定的手机号："+phoneNum);
	//读秒
	readSecond();
	//重发
	$(".phonerightpan").click(function(){
		repeat();
		subPhoneNum(phoneNum);
	});
	$('.phonebtn').click(function() {
		var $captcha = $('.phonetxt').val();
		var $phone = "<?=$this->phone ?>";
	    $.post( '/goods/setbinding',{'captcha':$captcha,'phone':$phone},function( result ) {
	        if ( result.success == 1 ) {
		        //alert( result.data );
		        window.location.href = '/goods/userinfo';
	        } else {
		        alert( result.error );
	        }
		},'json')
	})
	
	
</script>
</body>

<script>
//analytics
(function(i, s, o, g, r, a, m) {
	i['GoogleAnalyticsObject'] = r;
	i[r] = i[r] || function() {
		(i[r].q = i[r].q || []).push(arguments)
	}, i[r].l = 1 * new Date();
	a = s.createElement(o),
		m = s.getElementsByTagName(o)[0];
	a.async = 1;
	a.src = g;
	m.parentNode.insertBefore(a, m)
})(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

ga('create', 'UA-71370659-1', 'auto');
ga('send', 'pageview');
</script>
</html>