<!DOCTYPE HTML>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0"/>
<meta name="apple-mobile-web-app-capable" content="yes"/>
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<title>订单信息</title>
<link href="/css/swiper.min.css" rel="stylesheet" type="text/css" />
<link href="/css/style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/js/jquery-1.9.1.js"></script>
<script type="text/javascript" src="/js/function.js"></script>
</head>
<body class="graybody">
<form>
    <div class="orderbox overf">
    	<div class="orderTop overf">
    		<span class="fr orderTopIco"></span>
    		<dl class="orderTopdl">
    			<dt><img src="<?=$this->goods['goodsImg'][0]['imgurl'] ?>" /></dt>
    			<dd>订单号：<?=$this->order['orderCode'] ?></dd>
    			<dd><?=$this->goods['name'] ?></dd>
    		</dl>	
    	</div>
    	<ul class="orderul">
    		<li class="orderlibor overf">
    			<span class="orderliIco fl addressIco"></span>
    			<div class="orderlidiv">
    				<span class="orderliright fr orderlieditIco"></span>
    				<div class="orderlidivcen">
    					<h4>收货地址</h4>
    					<div class="orderpro">
    						<p class="addruser"></p>
    						<p class="addraddress"></p>
    					</div>
    				</div>
    			</div>
    		</li>
    		<li class="orderlibor overf">
    			<span class="orderliIco fl sendIco"></span>
    			<div class="orderlidiv">
    				<span class="orderliright fr orderlitxt">包邮</span>
    				<div class="orderlidivcen">
    					<h4>送货方式</h4>
    				</div>
    			</div>
    		</li>
    		<li class="overf">
    			<span class="orderliIco fl remarkIco"></span>
    			<div class="orderlidiv">
    				<div class="orderlidivcen">
    					<h4>备注</h4>
    				</div>
    			</div>
    			<div class="orderremarkarea"><textarea class="" name="remark" placeholder="请输入备注信息"></textarea></div>
    			<p class="allprice">总金额：<span><?=$this->order['price'] ?></span></p>
    		</li>
    	</ul>
    	<div class="orderbottombg"></div>
    </div>
    <input type="button" class="phonebtn orderbtn submitbtn" value="提交订单">
</form>

<script>
$('.submitbtn').click(function(){
	$.post('/goods/consignee',$('form').serialize(),function( result ) {
	    if ( result.success == 1 ) {
		    //alert( result.data );
		    window.location.href = '/order/index';
	    } else {
		    alert( result.error );
	    }
	},'json')
})
</script>

<!-- 模态框（Modal） -->
<div class="window-overlay tx addresshidebox">
	<div class="window-overlaybg"></div>
	<div class="window">
		<div class="deliveryaddress">
			<span class="deliclose"></span>
			<dl class="addressTopdl">
				<dt><img src="/images/bg05.png" /></dt>
				<dd>收货地址列表</dd>
			</dl>
			<div class="deliverlist">
<!-- 				<dl class="delivedl active"> -->
<!-- 					<dt class="deliIco fl"></dt> -->
<!-- 					<dd><span>帆</span>13699294500<span class="deleteAdress">删除</span></dd> -->
<!-- 					<dd>北京市朝阳区达成国际中心d座506B</dd> -->
<!-- 				</dl> -->
<!-- 				<dl class="delivedl"> -->
<!-- 					<dt class="deliIco fl"></dt> -->
<!-- 					<dd><span>杨</span>13699294500<span class="deleteAdress">删除</span></dd> -->
<!-- 					<dd>北京市朝阳区达成国际中心d座506B</dd> -->
<!-- 				</dl> -->
				
			</div>
			<span class="addressbtn">+新增地址</span>
			
			<div class="deliverbtnbox overf selectbtn">
				<span class="delibtn fl wailibtn graybtn">取消</span>
				<span class="delibtn fr wailibtn transbtn changeAdress">确定</span>
			</div>
		</div>
	</div>
</div>

<div id="addressdiv" style="display:none;">
<div class="adressform overf">
	<ul>
		<li><input type="text" class="fl adresput nameput" placeholder="收件人姓名" /><input type="text" class="fl telphput adresput" placeholder="联系电话" /></li>
		<li>
			<div class="cityselect"> 
				<select class="prov" id="province">
				    <option value="">请选择省份</option>
    				<?php foreach ($this->province as $v): ?>
    					<option value="<?=$v['name'] ?>"><?=$v['name'] ?></option>
    				<?php endforeach; ?>
				</select>  
				<select class="city" id="city">
				    <option value="">请选择城市</option>
				</select> 
				<select class="dist" id="area">
				    <option value="">请选择地区</option>
				</select> 
			</div> 
		</li>
		<li><input type="text" class="fl adresput detailput" placeholder="详细地址" /></li>
		<li class="adressformlibtn">
			<span class="delibtn fl graybtn resetdrebtn">取消</span>
			<span class="delibtn fr transbtn adddrebtn" id="">添加</span>
		</li>
	</ul>
</div>
</div>
<!-- <script type="text/javascript" src="/js/jquery.cityselect.js" ></script> -->
</body>

<script type="text/javascript">
    $(document).on("change", '#province',function() {
    	var province = $(this).val();
        var city = $('#city');
        var area = $('#area');
        city.html('<option value="">请选择城市</option>');
        area.html('<option value="">请选择地区</option>');
        $.post('/goods/city',{'province':province},function(result) {
        	var html = '';
            if(result.success == 1) {
               	html += '<option value="">请选择城市</option>';
              	for(var i=0;i<result.data.length;i++){
              	    html += '<option value="'+result.data[i].name+'">'+result.data[i].name+'</option>';
              	}
            } else {
               html += '<option value="">请选择城市</option>';
            }
        	city.html(html);
        },'json')
    });
    $(document).on("change", '#city',function() {
    	var city = $(this).val();
        var area = $('#area');
        area.html('<option value="">请选择地区</option>');
        $.post('/goods/area',{'city':city},function(result) {
        	var html = '';
            if(result.success == 1) {
               	html += '<option value="">请选择地区</option>';
              	for(var i=0;i<result.data.length;i++){
              	    html += '<option value="'+result.data[i].name+'">'+result.data[i].name+'</option>';
              	}
            } else {
               html += '<option value="">请选择地区</option>';
            }
        	area.html(html);
        },'json')
    });
</script>
</html>