


<div class="wrapper">
    <div id="main" class="container-fluid">
<!-- BreadNav -->
            <div class="row mt10">
                <div class="col-xs-12">
                    <div class="BreadcrumbNav white">
                        <a href="">首页</a>
                        >
                        <a href="">渠道商品</a>
                        >
                        <a href="">
                            <?php if( $this->showType == 'list' ):?>
                                商品列表
                            <?php elseif( $this->showType == 'choice' ):?>
                                分销渠道
                            <?php else:?>
                                渠道负责人
                            <?php endif;?>
                        </a>
                    </div>
                    
                </div>
            </div>
            <?php if( $this->showType == 'list' ):?>
                <?php include( realpath(dirname(__FILE__)).'/index_list.phtml' ); ?>
            <?php elseif( $this->showType == 'choice' ):?>
                <?php include( realpath(dirname(__FILE__)).'/index_choice.phtml' ); ?>
            <?php else:?>
                <?php include( realpath(dirname(__FILE__)).'/index_manager.phtml' ); ?>
            <?php endif;?>