	
	<form action="" method="get" id="submit"></form>

		<div class="row avatar pdl15 pdr15">
			<div class="neworder-info mt10 ">
                            <div class="choice-tit">
                                    <form action="" method='get'>
                                        <span class="btn btn-default change">切换负责人</span>

                                    </form>
                            </div>

                            <?php if( $this->dis ):?>
                                    <?php foreach( $this->dis as $row ):?>
                                            <div class="col-sm-6 col-lg-4 col-lg mt10 channel" data="<?=$row['id']?>">
                                                    <div class="avatar-wrap">
                                                            <div class="fl"><img src="<?=$row['headimgurl']?>"/></div>
                                                            <div class="fr">
                                                                    <p class="avatar-tit"><?=$row['name']?></p>
                                                                    <p>仓库中商品SKU数量<span><?=$row['passTotal']?></span></p> 
                                                                    <p>上架商品SKU数量<span><?=$row['sellplanTotal']?></span></p>
<!--                                                                    <p>库存金额<span><?=$row['costTotal']?></span></p>
                                                                    <p>渠道负责人<span><?=$row['manager']?></span></p> -->
                                                            </div>
                                                    </div>
                                            </div>
                                    <?php endforeach;?>
                            <?php endif;?>
                            <div class="clearfix"></div>
                        </div>
		</div>

	</div>
</div>

<script type="text/javascript">
	$('.channel').bind({
		click:function(){
			var channel = $(this).attr('data');
			var $form = $('#submit');
			$form.append("<input type='hidden' name='channel' value='"+channel+"' />");
			$form.append("<input type='hidden' name='showType' value='list' />");
                        $form.append("<input type='hidden' name='devId' value='<?=$this->devId;?>' />");
			$form.submit();
		}
	})
        $('.change').bind({
            click:function(){
                var $form = $(this).parent();
                $form.children().remove();
                $form.append("<input type='hidden' name='showType' value='manager' />");
                $form.submit();
            }
        })
	window.onload=function(){
		var $img = $('.avatar-wrap').children('.fl').children('img');
		for(var i=0;i<$img.length;i++){
			var width = $img.eq(i).parent().siblings().height() - $img.eq(i).height() + 10;
			if(width>0){
				$img.eq(i).css('margin-top',width/2+'px');
			}
		}
	}
</script>