
<script type="text/javascript" src="/upload/js/jquery.uploadify.min.js"></script>


<div class="wrapper">
    <div id="main" class="container-fluid">
<!-- BreadNav -->
            <div class="row mt10">
                <div class="col-xs-12">
                    <div class="BreadcrumbNav white">
                        <a href="">首页</a>
                            >
                        <a href="">采购管理</a>
                            >
                        <a href="">发货管理</a>
                    </div>
                </div>
            </div>
            <div class="row mt10">
<!-- search -->            
                <div class="tabhead col-sm-12">
<form action="" method='get'>
                    <span class="block top-search btn btn-primary" id="batchExport">批量导出</span>
                
                    <div class="btn-group btn-search">
                        <span class="btn btn-default dropdown-toggle">模糊查询<i class="caret"></i></span>
                        <ul class="batch-menu">
                            <li data="1">模糊查询</li>
                            <li data="2">按sku查询</li>
                            <li data="3">按货号查询</li>
                            <li data="4">按订单号查询</li>
                        </ul>
                    </div>
<input type="hidden" name="searchType" id="searchType" value="<?=$this->searchType;?>" />
<input type="hidden" name="topLevel" value="<?=$this->topLevel;?>" />
<input type="hidden" name="orderType" value="<?=$this->orderType;?>" />
<input type="hidden" name="showType" value="<?=$this->showType;?>" />
                    <div class="btn-group">
                        <div class="input-group">
                            <input class="block form-control" type="text"  value="<?=$this->keyword?>" name="keyword" placeholder="请输入关键词" />
                            <div class="input-group-btn">
                                <button class="btn btn-default" id='lowSearch'>搜索</button>
                            </div>
                        </div>
                    </div>
                <!-- high-search -->
                    <div class="btn-group fl top-search">
                        <span type="button" class="btn btn-primary">高级搜索</span>
                        <span id="batch" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="caret"></span>
                        </span>
                        <div class="high-search batch-menu">
                            <div class="row mt10">
                                <div class="col-xs-12">
                                    <span class="block linheit top-search">订单状态：</span>
                                    <select name="showType1" class="block form-control top-search">
                                        <option value="" <?php if($this->showType == '') echo "selected = 'selected'" ?>>全部</option>
                                        <option value="cancel" <?php if($this->showType == 'cancel') echo "selected = 'selected'" ?>>已取消</option>
                                        <option value="take" <?php if($this->showType == 'take') echo "selected = 'selected'" ?>>已签收</option>
                                        <option value="waitTake" <?php if($this->showType == 'waitTake') echo "selected = 'selected'" ?>>待签收</option>
                                        <option value="waitDeliver" <?php if($this->showType == 'waitDeliver') echo "selected = 'selected'" ?>>待发货</option>
                                        <option value="waitPay" <?php if($this->showType == 'waitPay') echo "selected = 'selected'" ?>>待付款</option>
                                    </select>
                                </div>
                            </div>

                            <div class="row mt10">
                                <div class="col-xs-12">
                                    <span class="block linheit top-search">退货状态：</span>
<select name="showType2" class="block form-control top-search">
    <option value="" <?php if($this->showType === '') echo "selected = 'selected'" ?>>全部</option>
    <option value="reback" <?php if($this->showType == 'reback') echo "selected = 'selected'" ?>>已退货</option>
    <option value="" <?php if($this->showType != 'reback') echo "selected = 'selected'" ?>>未退货</option>
</select>
                                </div>
                            </div>

                            <div class="row mt10">
                                <div class="col-xs-12">
                                    <span class="block linheit top-search">分销渠道：</span>
<select name="dist" class="block form-control top-search">
    <option value="" <?php if($this->showType == '') echo "selected = 'selected'" ?>>全部</option>
    <?php foreach ( $this->dis as $v ): ?>
        <option value="<?=$v['id'] ?>" <?php if($this->dist == $v['id']) echo "selected = 'selected'" ?>><?=$v['name'] ?></option>
    <?php endforeach; ?>
</select>
                                </div>
                            </div>

                            <div class="row mt10">
                                <div class="col-xs-12">
                                    <span class="block linheit top-search">下单时间：</span>
                                    <input name="starttime" id="indate" class="top-search form-control" type="text" placeholder="请输入日期" value="<?=$this->starttime?>" readonly/>
                                    <span class="block linheit top-search"> - </span>
                                    <input name="endtime" id="indate2" class="top-search form-control" type="text"  placeholder="请输入日期" value="<?=$this->endtime?>" readonly/>
                                </div>
                            </div>
                            <div class="row mt10">
                                <div class="col-xs-12">
                                    <button class="btn btn-primary fr disguise">搜索</button>
                                </div>
                            </div>
                        </div>
                    </div>

<!-- high-search -->
</form>
<script>
    $('#batchExport').bind({
        click:function(){
            var $form = $(this).parent();
            $form.attr('action','/deliver/exporttext');
            $form.submit();
            $form.attr('action','');
            return false;
        }
    });
</script>
                <div class="setwrap">
                    <button id="setWindow" class="btn btn-primary">列设置</button>
                    <div class="set-window">
                    
                    </div>
                </div>
<!--                <span class="linheit top-search">数量：<i class='red'><?=$this->total;?></i></span>
                <span class="linheit top-search">金额：<i class='red'><?=$this->price;?></i></span>-->
            </div>
            <div class="row mt10 checkTab-ul">
                <div class="col-xs-12">
                    <ul>
                        <a href="?keyword=<?=$this->keyword;?>&channel=<?=$this->channel;?>&time=<?=$this->time;?>&topLevel=pingtai&orderType="><li class="checkTab-btn <?php if($this->topLevel=='pingtai' || !$this->topLevel) echo 'active' ?>" id="stocking"><p>平台商品<span class="hidden">0</span></p></li></a>
                        <a href="?keyword=<?=$this->keyword;?>&channel=<?=$this->channel;?>&time=<?=$this->time;?>&topLevel=taobao&orderType=4"><li class="checkTab-btn <?php if($this->topLevel=='taobao') echo 'active' ?>"id="showing"><p>代销商品<span class="hidden">0</span></p></li></a>
                        <div class="clearfix"></div></a>
                    </ul>
                </div>
            </div>
                <!-- 二级标签 -->
            <div class="row mt10 finance-ul">
                <div class="col-xs-12 two-tab">
                    <ul>
                        <?php if( $this->topLevel == 'taobao' ):?>
                            <li class="finance-btn <?php if ( $this->showType == 'waitBuy') echo ' active '; ?> "><a href="?topLevel=<?=$this->topLevel;?>&showType=waitBuy&status=4&isBuyer=0&keyword=<?=$this->keyword;?>&starttime=<?=$this->starttime;?>&endtime=<?=$this->endtime;?>&dist=<?=$this->dist;?>&orderType=<?=$this->orderType?>"><p>待采购<span><?=$this->total['waitBuy']['totalNum']?></span></p></a></li>
                        <?php endif;?>
                        <li class="finance-btn <?php if ($this->showType == 'waitDeliver') echo ' active '; ?> "><a href="?topLevel=<?=$this->topLevel;?>&showType=waitDeliver&status=4&keyword=<?=$this->keyword;?>&starttime=<?=$this->starttime;?>&endtime=<?=$this->endtime;?>&dist=<?=$this->dist;?>&orderType=<?=$this->orderType?>"><p>待发货<span><?=$this->total['waitDeliver']['totalNum']?></span></p></a></li>
                        <li class="finance-btn <?php if ($this->showType == 'waitTake') echo ' active '; ?> "><a href="?topLevel=<?=$this->topLevel;?>&showType=waitTake&status=3&keyword=<?=$this->keyword;?>&starttime=<?=$this->starttime;?>&endtime=<?=$this->endtime;?>&dist=<?=$this->dist;?>&orderType=<?=$this->orderType?>"><p>待签收<span><?=$this->total['waitTake']['totalNum']?></span></p></a></li>
                        <li class="finance-btn <?php if ($this->showType == 'take') echo ' active '; ?> "><a href="?topLevel=<?=$this->topLevel;?>&showType=take&status=2&keyword=<?=$this->keyword;?>&starttime=<?=$this->starttime;?>&endtime=<?=$this->endtime;?>&dist=<?=$this->dist;?>&orderType=<?=$this->orderType?>"><p>已签收<span><?=$this->total['take']['totalNum']?></span></p></a></li>
                        <li class="finance-btn <?php if ($this->showType == 'brush') echo ' active '; ?> "><a href="?topLevel=<?=$this->topLevel;?>&showType=brush&status=7&keyword=<?=$this->keyword;?>&starttime=<?=$this->starttime;?>&endtime=<?=$this->endtime;?>&dist=<?=$this->dist;?>&orderType=<?=$this->orderType?>"><p>到店取货<span><?=$this->total['brush']['totalNum']?></span></p></a></li>
                        <li class="finance-btn <?php if ($this->showType == 'cancel') echo ' active '; ?> "><a href="?topLevel=<?=$this->topLevel;?>&showType=cancel&status=1&keyword=<?=$this->keyword;?>&starttime=<?=$this->starttime;?>&endtime=<?=$this->endtime;?>&dist=<?=$this->dist;?>&orderType=<?=$this->orderType?>"><p>已取消<span><?=$this->total['cancel']['totalNum']?></span></p></a></li>
                        <li class="finance-btn <?php if ($this->showType == 'reback') echo ' active '; ?> "><a href="?topLevel=<?=$this->topLevel;?>&showType=reback&reback=reback&keyword=<?=$this->keyword;?>&starttime=<?=$this->starttime;?>&endtime=<?=$this->endtime;?>&dist=<?=$this->dist;?>&orderType=<?=$this->orderType?>"><p>退货<span><?=$this->total['reback']['totalNum']?></span></p></a></li>
                        <li class="finance-btn <?php if ($this->showType == 'deleteStore') echo ' active '; ?> "><a href="?topLevel=<?=$this->topLevel;?>&showType=deleteStore&status=6&keyword=<?=$this->keyword;?>&starttime=<?=$this->starttime;?>&endtime=<?=$this->endtime;?>&dist=<?=$this->dist;?>&orderType=<?=$this->orderType?>"><p>订单回收站<span><?=$this->total['deleteStore']['totalNum']?></span></p></a></li>
                        <!--<li class="finance-btn <?= $this->orderType ? 'active' : ''; ?> " ><a href="?topLevel=<?=$this->topLevel;?>&status=&dist=32&orderType=4&keyword=<?=$this->keyword;?>&starttime=<?=$this->starttime;?>&endtime=<?=$this->endtime;?>"><p>淘宝订单<span><?=$this->totalTaoBao?></span></p></a></li>-->
                        <div class="clearfix"></div>
                    </ul> 
                </div>                
            </div>
        </div>
        <div class="row tablescroll">
                
                <table class="tablewidth scrollTable" id="table">
                    <thead>
                        <tr>
                            <td><input id="checkBox" type="checkbox" />全选</td>
                            <td>订单来源</td>
                            <td>订单编号
                                <?php if($this->topLevel == 'taobao' && $this->showType != 'waitBuy' ):?>
                                    /追踪号
                                <?php endif;?>
                            </td>
                            <td>图片</td>
                            <td>下单时间</td>
                            <td>商品</td>
                            <td>SKU编码</td>
                            <td class="none">货号</td>
                            <td>实付价格</td>
                            <td>渠道</td>
                            <?php if ( $this->showType != 'waitDeliver' ) :?>
                            <td>发货时间</td>
                            <?php endif;?>
                            <?php if ( ( $this->showType != 'brush' || $this->showType == 'reback' ) && $this->showType != 'waitBuy' )  : ?>
                                <td>物流信息</td>
                            <?php endif;?>
                            <td>下单人
                                <?php if( $this->topLevel == 'taobao' && $this->showType != 'waitBuy' ):?>
                                    /采购人
                                <?php endif;?>
                            </td>
                            <td>操作</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="order-data ">
                            <td colspan="20"><span>今天<i>▲</i></span></td>
                        </tr>
                        <?php if($this->todaylist):?>
                        <?php foreach ($this->todaylist as $row): ?>
                            <tr class="text-center row_<?=$row['id']?>">
                                <td><input type="checkbox" /></td>
                                <td>
                                    <?php 
                                    if ( $row['isBrush'] ) {
                                        echo "到店取货";
                                    }else{
                                        if( $row['orderType'] == 4 ){
                                            echo "代销订单";
                                        }else{
                                            if ( $row['sellType'] == 0 ) {
                                                echo "平台下单";
                                            }elseif ( $row['sellType'] == 4 ){ 
                                                echo "app下单";
                                            }elseif ( $row['sellType'] == 5 ) { 
                                                echo "微信下单";
                                            }
                                        }
                                    }?> 
                                </td>
                                <td class="orderCode">
                                    <p><?=$row['orderCode']?></p>
                                    <p>
                                        <?php if( $row['trackCode'] ):?>
                                            【 <?=$row['trackCode']?> 】
                                        <?php else:?>
                                            <?php if( $this->topLevel == 'taobao' && $this->showType != 'waitBuy' ):?>
                                            【 未采购 】
                                            <?php endif;?>
                                        <?php endif;?> 
                                    </p>
                                </td>
                                <td>
                                    <img onclick='showImg(this)' src="<?=$row['imageurl'];?>" width="80px" height="60px">
                                </td>
                                <td><?php if( $row['payTime'] ) echo date('y-m-d H:i',$row['payTime']); else echo '';?></td>
                                <td><?=$row['name']?></td>
                                <td><?=$row['code']?></td>
                                <td class="none"><?=$row['goodsNo']?></td>
                                <td class="orderPrice"><?=$row['orderPrice'];?></td>
                                <td><?=$row['cname'] ? $row['cname'] :'无';?></td>
                                <?php if ( $this->showType != 'waitDeliver' ) :?>
                                    <td><?php if( $row['deliverTime'] ) echo date('y-m-d H:i',$row['deliverTime']); else echo '';?></td>
                                <?php endif;?>
                                <!-- <td width="60px" class="orderstatus"><?=$row['payStatus']?></td>
                                <td width="60px" class="rebackstatus"><?php if ($row['reback'] == 1) echo '此单已退'; ?></td> -->

                                <?php if ( ( $this->showType != 'brush' || $this->showType == 'reback' ) && $this->showType != 'waitBuy' )  : ?>
                                    <td>
                                        <?php if ( !$row['express'] ) : ?>
                                            <span class="logistics-btn" onclick="logistics(this)">未设置</span>
                                        <?php else : ?>
                                            <p><span class="form-group">
                                                <i id="express2" class="logistics-type">
                                                </i>【
                                                <i id="expressNum2" class="logistics-btn" onclick="logistics(this)">
                                                    <?=$row['express']['number'] ? $row['express']['number'] : "无"?>
                                                </i>】
                                            </span></p>
                                        <?php endif;?>
                                    </td>
                                <?php endif;?>
                                    
                                <td>
                                    <p><?php echo $row['operator']?$row['operator']:'【无】'?></p>
                                    <?php if( $this->topLevel == 'taobao' && $this->showType != 'waitBuy' ):?>
                                        <p><?php echo $row['buyer']?$row['buyer']:'【无】'?></p>
                                    <?php endif;?>
                                </td>
                                <td data="<?=$row['id']?>">
                                    
                                    <div class="order_menu">
                                    <span toggle='yes' data="<?=$row['id']?>" class="btn-orderDetails btn btn-default"><img src="/img/eye.png"/><i>预览</i></span>
                                        <div class="btn-group btn-search">
                                                <?php if( $this->topLevel == 'taobao' && $this->showType == 'waitBuy' ):?>
                                                    <span class="btn btn-default buyerShow">订单采购</span>
                                                <?php else:?>
                                                    <?php if( $this->showType != 'reback' ):?>
                                                    <span class="btn btn-default dropdown-toggle">请选择<i class="caret"></i></span>
                                                    <ul class="batch-menu">
                                                       <a class="edit1"><li><img src="/img/xiugai.png">修改实付价格</li></a>
                                                       <a class="edit2"><li><img src="/img/bianji.png">修改附加价格</li></a>
                                                    </ul>
                                                    <?php endif;?>
                                                <?php endif;?>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        <?php endif;?>
                        <tr class="order-data">
                            <td colspan="20"><span>更早<i>▲</i></span></td>
                        </tr>
                        <?php if($this->earlylist):?>
                        <?php foreach ($this->earlylist as $row): ?>
                            <tr class="text-center row_<?=$row['id']?>">
                                <td><input type="checkbox" /></td>
                                <td>
                                    <?php 
                                    if ( $row['isBrush'] ) {
                                        echo "到店取货";
                                    }else{
                                        if( $row['orderType'] == 4 ){
                                            echo "代销订单";
                                        }else{
                                            if ( $row['sellType'] == 0 ) {
                                                echo "平台下单";
                                            }elseif ( $row['sellType'] == 4 ){ 
                                                echo "app下单";
                                            }elseif ( $row['sellType'] == 5 ) { 
                                                echo "微信下单";
                                            }
                                        }
                                    }?> 
                                </td>
                                <td class="orderCode">
                                    <p><?=$row['orderCode']?></p>
                                    <p>
                                        <?php if( $row['trackCode'] ):?>
                                            【 <?=$row['trackCode']?> 】
                                        <?php else:?>
                                            <?php if( $this->topLevel == 'taobao' && $this->showType != 'waitBuy' ):?>
                                            【 未采购 】
                                            <?php endif;?>
                                        <?php endif;?> 
                                    </p>
                                </td>
                                <td>
                                    <img onclick='showImg(this)' src="<?=$row['imageurl'];?>" width="80px" height="60px">
                                </td>
                                <td><?php if( $row['payTime'] ) echo date('y-m-d H:i',$row['payTime']); else echo '';?></td>
                                <td><?=$row['name']?></td>
                                <td><?=$row['code']?></td>
                                <td class="none"><?=$row['goodsNo']?></td>
                                <td class="orderPrice"><?=$row['orderPrice'];?></td>
                                <td><?=$row['cname'] ? $row['cname'] :'无';?></td>
                                <?php if ( $this->showType != 'waitDeliver' ) :?>
                                    <td><?php if( $row['deliverTime'] ) echo date('y-m-d H:i',$row['deliverTime']); else echo '';?></td>
                                <?php endif;?>
                                <!-- <td width="60px" class="orderstatus"><?=$row['payStatus']?></td>
                                <td width="60px" class="rebackstatus"><?php if ($row['reback'] == 1) echo '此单已退'; ?></td> -->

                                <?php if ( ( $this->showType != 'brush' || $this->showType == 'reback' ) && $this->showType != 'waitBuy' )  : ?>
                                    <td>
                                        <?php if ( !$row['express'] ) : ?>
                                            <span class="logistics-btn" onclick="logistics(this)">未设置</span>
                                        <?php else : ?>
                                            <p><span class="form-group">
                                                <i id="express2" class="logistics-type">
                                                </i>【
                                                <i id="expressNum2" class="logistics-btn" onclick="logistics(this)">
                                                    <?=$row['express']['number'] ? $row['express']['number'] : "无"?>
                                                </i>】
                                            </span></p>
                                        <?php endif;?>
                                    </td>
                                <?php endif;?>
                                    
                                <td>
                                    <p><?php echo $row['operator']?$row['operator']:'【无】'?></p>
                                    <?php if( $this->topLevel == 'taobao' && $this->showType != 'waitBuy' ):?>
                                        <p><?php echo $row['buyer']?$row['buyer']:'【无】'?></p>
                                    <?php endif;?>
                                </td>
                                <td data="<?=$row['id']?>">
                                    
                                    <div class="order_menu">
                                    <span toggle='yes' data="<?=$row['id']?>" class="btn-orderDetails btn btn-default"><img src="/img/eye.png"/><i>预览</i></span>
                                        <div class="btn-group btn-search">
                                                <?php if( $this->topLevel == 'taobao' && $this->showType == 'waitBuy' ):?>
                                                    <span class="btn btn-default buyerShow">订单采购</span>
                                                <?php else:?>
                                                    <?php if( $this->showType != 'reback' ):?>
                                                    <span class="btn btn-default dropdown-toggle">请选择<i class="caret"></i></span>
                                                    <ul class="batch-menu">
                                                       <a class="edit1"><li><img src="/img/xiugai.png">修改实付价格</li></a>
                                                       <a class="edit2"><li><img src="/img/bianji.png">修改附加价格</li></a>
                                                    </ul>
                                                    <?php endif;?>
                                                <?php endif;?>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        <?php endif;?>
                        <tr class="none" id="orderDetail">
                            <td colspan="16">
                                    <input class="orderId" type="hidden" name="id" value=""> 
                                    <div class="col-lg-10 col-lg-offset-1 mt10 neworder-info">
                                        <h4 class="tit linheit">客户信息</h4>
                                        <hr />
                                        <div class="row mt10 childpad">
                                            <label class="col-lg-1 col-md-2 control-label">客户姓名</label>
                                            <div class="col-sm-4">
                                                <input name="consignee" value="" class="form-control" id="consignee" readonly/>
                                            </div>
                                            <label class="col-md-2 col-lg-1 control-label">手机号码</label>
                                            <div class="col-sm-4">
                                                <input name="phone" class="form-control" id="phone"  value="" readonly/>
                                            </div>
                                        </div>
                                        <div class="row mt10 childpad">
                                            <label class="col-md-2 col-lg-1 col-xs-12 control-label">详细地址</label>
                                            <div class="col-xs-12 col-md-10">
                                                <div class="cityselect fl mr20"> 
                                                    <select name="province" class="form-control" id="province" disabled>
                                                        <option></option>
                                                    </select>
                                                    <select name="city" class="form-control" id="city" disabled>
                                                        <option></option>
                                                    </select>
                                                    <select name="area" class="form-control" id="area" disabled>
                                                        <option></option>
                                                    </select>
                                                </div>
                                                <input name="address" class="form-control width500 fl" value="" id="address" readonly/>
                                            </div>
                                        </div>
                                        <div class="row mt10 childpad">
                                            <label class="col-md-2 col-lg-1 control-label">买家备注</label>
                                            <div class="col-md-10 col-lg-9">
                                                <textarea id="remark" name="remark" readonly></textarea>
                                            </div>
                                        </div>
                                        <div class="row mt10 childpad">
                                            <label class="col-md-2 col-lg-1 control-label">卖家备注</label>
                                            <div class="col-md-10 col-lg-9">
                                                <textarea id="sellerremark" name="sellerremark" readonly></textarea>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-10 col-lg-offset-1 mt10 neworder-info">
                                        <h4 class="tit linheit">商品信息</h4>
                                        <hr />
                                        <div class="row mt10 table-responsive">
                                            <table class="table table-bordered">
                                                <tr>
                                                    <td>商品图</td>
                                                    <td>商品名称</td>
                                                    <td>商品参数</td>
                                                    <td>货号</td>
                                                    <td>SKU编码</td>
                                                    <td>数量</td>
                                                    <td>结算价格</td>
                                                    <td>实付价格</td>
                                                </tr>
                                                <tr>
                                                    <td id="goodsImg"><img src=""/></td>
                                                    <td id="goodsName"></td>
                                                    <td id="attribute"></td>
                                                    <td id="goodsNo"></td>
                                                    <td id="code"></td>
                                                    <td id="number"></td>
                                                    <td id="purchPrice"></td>
                                                    <td id="orderPrice"></td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
    
            </div>
        <!-- page -->
        <div class="row center mb10">
            <div class="pagenav">
                <div id="Pagination" class="flickr">
                    <?=$this->pagebar;?>
                </div>
                <div class="page-count">
                    <div>
                        每页显示<span id="perpage"><?=$this->perpage?></span>条
                        <ul id="pageCountSelect">
                            <li>-- 请选择 --</li>
                            <li>30</li>
                            <li>50</li>
                            <li>100</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
<!-- page-end -->
<!-- 修改价格窗口 -->
<div class="modal editPrice">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">请输入数量</h4>
            </div>
            <form method="post" id="orderForm">
                <input type="hidden" name="orderId" id="orderId">
                <div class="modal-body body1">
                    <div class="col-xs-6 col-xs-offset-2">
                        <div class="inp-tit text-center">原实付价格</div>
                        <div class="inp-inp">
                            <div>
                                <input class="form-control" type="text" id="formPrice" disabled/>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-xs-offset-2 mt10">
                        <div class="inp-tit text-center">实付价格</div>
                        <div class="inp-inp">
                            <div>
                                <input class="form-control" type="text" name="orderPrice" />
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="modal-body body2">
                    <div class="row modal-row">
                        <div class="col-sm-6 mt10">
                            <div class="inp-tit text-center">实付运费</div>
                            <div class="inp-inp">
                                <div>
                                    <input id="real_freight" name="real_freight" class="form-control" type="text" value="" />
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 mt10">
                            <div class="inp-tit text-center">实付包装费用</div>
                            <div class="inp-inp">
                                <div>
                                    <input id="real_pack" name="real_pack" class="form-control" type="text" value="" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row modal-row">
                        <div class="col-sm-6 mt10">
                            <div class="inp-tit text-center">实付证书费用</div>
                            <div class="inp-inp">
                                <div>
                                    <input id="real_certificate" name="real_certificate" class="form-control" type="text" value="" />
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 mt10">
                            <div class="inp-tit text-center">实付其他费用</div>
                            <div class="inp-inp">
                                <div>
                                    <input id="real_other" name="real_other" class="form-control" type="text" value="" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <span class="btn btn-default" data-dismiss="modal">取消</span>
                    <button id="btnSubmit" type="button" class="btn btn-primary" data="" >确定</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- 订单采购 start -->
<form id="orderBuyer" action="/order/buyer" method="post">
    <input type="hidden" name="orderId"  value="">
    <div class="modal new-buy">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close"><span>&times;</span></button>
                            <img class="auto-img" src="/img/truck.png" />
                            <h4 class="modal-title text-center">新增采购记录</h4>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-sm-5 mb10 col-xs-offset-1">
                                    <div class="inp-tit text-center">姓名</div>
                                    <div class="inp-inp">
                                        <div>
                                            <select name="buyerId" class="form-control">
                                                <option value="<?=$this->_developer['id']?>" selected="selected"><?=$this->_developer['name']?></option>
                                            </select>

                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-5 mb10">
                                    <div class="inp-tit text-center">采购日期</div>
                                    <div class="inp-inp">
                                        <div>
                                            <input id="buyerTime" name="buyerTime" class="form-control" type="text" value=""/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row modal-row">
                                <div class="col-sm-7 mt10 col-xs-offset-1">
                                    <div class="inp-tit text-center">追踪号</div>
                                    <div class="inp-inp">
                                        <div>
                                            <input id="buyerCode" name="trackCode" class="form-control" type="text" value="" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <span class="hideOrderInfo btn btn-primary" id="buyer">确定</span>
                            <span class="hideOrderInfo btn btn-default" id="cancelBuyer">取消</span>
                        </div>
                    </div>
                </div>
            </div>
</form>
<!-- 订单采购 end -->
<!-- 修改价格窗口 -->
        <!--物流窗口-->
        <form name="fome5" method="POST" action="/deliver/deliver">
            <input class="orderId" type="hidden" name="id" value="">
            <input type="hidden" name="searchType" value="<?=$this->searchType?>">
            <input type="hidden" name="keyword" value="<?=$this->keyword?>">
<!--            <input type="hidden" name="status" value="<?=$this->status?>">
            <input type="hidden" name="reback" value="<?=$this->reback?>">-->
            <input type="hidden" name="showType" value="<?=$this->showType?>">
            <input type="hidden" name="dist" value="<?=$this->dist?>">
            <input type="hidden" name="starttime" value="<?=$this->starttime?>">
            <input type="hidden" name="endtime" value="<?=$this->endtime?>">
            <input type="hidden" name="perpage" value="<?=$this->perpage?>">
            <input type="hidden" name="page" value="<?=$this->page?>">
            <input type="hidden" name="topLevel" value="<?=$this->topLevel;?>" />
            <input type="hidden" name="orderType" value="<?=$this->orderType;?>" />
<!--            <input type="hidden" name="isBuyer" value="<?=$this->isBuyer;?>" />-->
            <div class="modal logistics">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close"><span>&times;</span></button>
                            <img class="auto-img" src="/img/truck.png" />
                            <h4 class="modal-title text-center">设置物流渠道</h4>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-sm-5 mt10 col-xs-offset-1">
                                    <div class="inp-tit text-center">快递公司</div>
                                    <div class="inp-inp">
                                        <div>
                                            <select id="express" name="express" class="form-control">
                                            <option value="">请选择</option>
                                            <?php foreach( $this->express as $exp ) : ?>
                                                <option value="<?=$exp['id']?>"><?=$exp['name']?></option>
                                            <?php endforeach;?>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-5 mt10">
                                    <div class="inp-tit text-center">运单编号</div>
                                    <div class="inp-inp">
                                        <div>
                                            <input id="expressNum" name="expressNum" class="form-control" type="text" value="" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <?php if ( $this->showType == 'waitTake' || $this->showType == 'waitDeliver' ) : ?>
                                <input id="sub5" value="发货" type="submit" class="btn btn-primary" name="sub5" />
                            <?php endif;?>
                            <span class="hideOrderInfo btn btn-default">取消</span>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!--导入订单-->
        <div id="importOrder" class="import-order modal-content none">
        <div class="container-fluid">
            <div class="modal-header">
                <button type="button" class="close"><span>&times;</span></button>
                <h4 class="modal-title">订单导入</h4>
                <p>提示信息</p>
            </div>
            <div class="row info-col">
                <div class="col-lg-12">
                    <div class="inp-tit">模板类型</div>
                    <div class="inp-inp">
                        <div>
                            <div class="order_menu fl">
                                <span class="btn-orderDetails btn btn-default active">标准模板</span>
                                <span class="btn btn-default dropdown-toggle">自制模板</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row info-col">
                <div class="col-lg-10">
                    <div class="inp-tit">平台类型</div>
                    <div class="inp-inp">
                        <div>
                            <select class="form-control">
                                <option>订单管理</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row info-col">
                <div class="col-lg-10">
                    <div class="inp-tit">模板</div>
                    <div class="inp-inp">
                        <div>
                            <select class="form-control">
                                <option>淘宝订单</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row info-col">
                <div class="col-lg-10">
                    <div class="inp-tit">上传模板文件</div>
                    <div class="inp-inp">
                        <div>
                            <input type="file" id="file_upload_excel" class="update" name="fileName"/>
                            
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="row info-col">
                <div class="col-xs-12 text-right">
                    <button class="btn btn-primary" id="uploadOrder">上传</button>
                    <span id="importCancel" class="btn btn-cancel">取消</span>
                </div>
            </div>
        </div>
    </div>
    <form action="/import/dispatch" id="upload" method="post" enctype="multipart/form-data">
        <input id="action" type="hidden" name="action" value="orderInsert">
        <input id="record" type="hidden" name="" value="" />
    </form>
    </div>
</div>
<script type="text/javascript" src="/js/test.js/jedate.min.js" ></script>

<script type="text/javascript">
    
    $(function() {
        //导入订单
        $('#orderImportBtn').click(function(){
            $('#importOrder').removeClass('none');
            $('#file_upload_excel,#file_upload_excel-button').css('width','100%');
            $('#importOrder .input-group').css('zIndex','-1');
            $('#SWFUpload_0').attr('width','260');
        })
        $('#file_upload_excel').uploadify({
            'multi'    : false,
            'swf'      : '../upload/uploadify.swf',
            'uploader' : '../upload/uploadify.php',
            'fileSizeLimit': '5120KB',
            'buttonText': '<div class="input-group"><input type="text" class="form-control inpwidth100"><div class="input-group-addon">浏览</div></div>', 
            'fileExt' : '*.xls; *.xlsx',
            'queueID'  : 'excel_file_queue',
            'onUploadSuccess' : function(file, data, response) {
                if(data==2){
                  $('#getvalsname1').html(file.name + '上传失败');
                  alert("上传失败");
                }else if(data){
                    var strs=data.split("||");
                    $("#record").attr('name','files['+strs[0]+']');
                    $("#record").val(file.name);
               }
            }
    	});
        $('#uploadOrder').click(function(){
            var content = $('#record').val();
            if(content){
                $.post($('#upload').attr('action'),$("#upload").serialize(),function(result){
                    if( result.success==1 ){
                        alert(result.data);
                        $('#step').find('li').eq(0).removeClass('active');
                        $('#step').find('li').eq(1).addClass('active');
                    }else{
                        alert( result.error );
                    }
                },'json');
            }else{
                alert('请选择上传文件');
            }
        });
        $('#importCancel').click(function(){
            $('#importOrder').addClass('none');
        });
        $('#importOrder .close').click(function(){
            $('#importOrder').addClass('none');
        })
        //订单采购
        $('.buyerShow').click(function(){
            $('.new-buy').show().css('margin-top','150px');
            var orderId = $(this).parents('td').eq(0).attr('data');
            $('#orderBuyer')[0].reset();
            $('#orderBuyer').find("input").eq(0).val(orderId);
        })
        //提交订单采购
        $('#buyer').click(function(){
            var buyerTime = $('#buyerTime').val();
            if( !buyerTime ){
                alert('请选择采购时间');
                return false;
            }
            var buyerCode = $('#buyerCode').val();
            if( !buyerCode ){
                alert('请输入订单追踪号');
                return false;
            }
            if( confirm('你确定要提交吗？') ){
                var $form = $('#orderBuyer');
                var id = $form.find('input').eq(0).val();
                $.post($form.attr('action'),$form.serialize(),function(result){
                    //console.log(result);
                    if( result.success == 1 ){
                        alert(result.data);
                        $('.row_'+id).remove();
                        var $from = $('.two-tab').find('li:eq(0)').find('span');
                        var f_oldNum = $from.text();
                        $from.text( --f_oldNum );
                        var $to = $('.two-tab').find('li:eq(1)').find('span');
                        var t_oldNum = $to.text();
                        $to.text( ++t_oldNum );
                    }else if( result.success == 2 ){
                        alert(result.notice);
                    }else{
                        alert(result.error);
                    }
                    $('.new-buy').hide();
                },'json');
               
            }
        })
    })
    //模糊搜索
    // $('#searchType').val(1);
    $('.tabhead .btn-search').children('.btn').click(function(e){
        e.stopPropagation();
        $(this).next().toggle();
    })
    $('.tabhead .btn-search').children('.btn').next('.batch-menu').children('li').click(function(){
        $('#searchType').val($(this).attr('data'));
        $('.tabhead .btn-search').children('.btn').html($(this).text() + '<i class="caret"></i>')
    })
    //设置物流
    function logistics(obj){
        $('.logistics').show().css('margin-top','150px');
        var $id = $(obj).parents('tr').children('td').last().find('span').attr('data');
        $('form[name="fome5"] .orderId').val($id);
        $.post('/deliver/getExpress',{id:$id},function(res){
            var $data = res.data;
            $('#express').children('option[value="'+$data.express.expressId+'"]').attr('selected','selected');
            $('#expressNum').val($data.express.number);
            // $('#real_freight').val($data.orderPrice.real_freight);
            // $('#real_pack').val($data.orderPrice.real_pack);
            // $('#real_certificate').val($data.orderPrice.real_certificate);
            // $('#real_other').val($data.orderPrice.real_other);
        },'json')
    }
    $('.modal').find('.close').click(function(){
        $('.modal').hide();
    })
    $('.modal').find('.btn-default').click(function(){
        $('.modal').hide();
    })
    //地址下拉
    /*$("#city").citySelect({
        nodata:"none",
        required:false
    });*/
    //高级搜索展开按钮点击
    $('#batch').click(function(e){
        e.stopPropagation();
        $(this).next().toggle();
    })
    $('#batch').next('.high-search').click(function(e){
        e.stopPropagation();
    })
    //普通搜索按钮
    $('#lowSearch').bind({
        click:function(){
            $('#highSearch').children().remove();
            $(this).parent().submit();
        }
    })
    //全选
    var checkAll = false;
    $("#checkBox").click(function(){
        if(!checkAll){
            $("#table").find("tr input").prop({"checked":true});
            checkAll = true;
        }else if(checkAll) {
            checkAll = false;
            $("#table").find("tr input").prop({"checked":false});
        }
    })
    var $btn = $('#table tbody').find('.btn-orderDetails');
    
    $btn.bind('click',function(){
        showOrderInfo($(this));
        var id = $(this).attr('data');
        var province = $('#province');
        var city = $('#city');
        var area = $('#area');
        var payway = $('#payway');
        var paytype = $('#paytype');
        var paybank = $('#paybank');
        $.post('/deliver/detail',{'id':id},function(result) {
            var attributeHtml = '';
            if(result.success == 1) {
                //客户信息
                $("form[name='fome1'] .orderId").val(result.data['id']);//id
                $("#deliver").val(result.data['deliverWay']);//快递
                $("#freight").val(result.data['price']['price_freight']);//运费
                $("#price_certificate").val(result.data['price']['price_certificate']);//证书
                $("#price_pack").val(result.data['price']['price_pack']);//包装
                $("#price_mount").val(result.data['price']['price_mount']);//装裱
                $("#price_other").val(result.data['price']['price_other']);//其他
                $("#realprice").val(result.data['order']['price']);//金额
                $("#consignee").val(result.data['uname']);//收货人
                $("#phone").val(result.data['tel']);//手机号

                province.children('option').html(result.data['province']);
                city.children('option').html(result.data['city']);
                area.children('option').html(result.data['area']);

                payway.children('option').html(result.data['payway']);
                paytype.children('option').html(result.data['paytype']);
                paybank.children('option').html(result.data['paybank']['name']);
                //收货地址
                $("#address").val(result.data['address']);
                //商品信息
                $("#goodsImg img").attr("src",result.data['goodsImg'])//商品图
                $("#goodsName").html(result.data['goodsName']);//商品名称
                $("#goodsNo").html(result.data['goodsNo']);//货号
                $("#code").html(result.data['order']['code']);//SKU
                $("#orderPrice").html(result.data['orderPrice']);//实付价格
                $("#pPrice").html(Math.ceil(result.data['order']['purchPrice']*result.data['order']['ptimes']));//平台价格
                $("#purchPrice").html(result.data['order']['purchPrice']*result.data['number']);
                $("#number").html(result.data['number']);
                if (result.data['attribute']){
                    for (var i = 0;i<result.data['attribute'].length; i++) {
                        if( result.data['attribute'][i]['value']['name'] != '0' ){
                            attributeHtml += "<p>"+result.data['attribute'][i]['key']['name']+":"+result.data['attribute'][i]['value']['name']+"<p>";
                        }
                    };
                    $('#attribute').html(attributeHtml);
                }
                $("#orderCode").val(result.data['orderCode']);//订单编号

                $("#payTime").val(getLocalTime(result.data['payTime']));//支付时间
                //备注信息
                $("#remark").val(result.data['remark']);
                $("#sellerremark").val(result.data['sellerremark']);
                
            }else if( result.success == 0 ){
                alert("获取信息失败");
            }else if( result.success == 2 ){
                alert(result.notice);
            }
        },'json')
    });


    function getLocalTime(nS) {     
        return new Date(parseInt(nS) * 1000).toLocaleString().replace(/:\d{1,2}$/,' ');     
    }
    function hideOrderDetail(){
        $('#orderDetail').prev().removeClass('active').find('.btn-orderDetails').attr('toggle','yes');
        $('#orderDetail').remove();
    }
    
//日期
jeDate({
    dateCell:"#indate",//isinitVal:true,
    format:"YYYY-MM-DD",
    isTime:false, //isClear:false,
    minDate:"1970-1-1 00:00:00"
})
jeDate({
    dateCell:"#indate2",//isinitVal:true,
    format:"YYYY-MM-DD",
    isTime:false, //isClear:false,
    minDate:"1970-1-1 00:00:00"
})
jeDate({
    dateCell:"#buyerTime",//isinitVal:true,
    format:"YYYY-MM-DD",
    isinitVal:true,
    isTime:false, //isClear:false,

})
    
//时间分类  
var $datalist = $('#table tbody .order-data').find('span');
    $datalist.click(function(){
        var start = $(this).parent().parent().index();
        var end = 0;
        var $child;
        for(var i=0;i<$datalist.length;i++){
            if($datalist.eq(i).parent().parent().index()==start && i<($datalist.length-1)){
                end = $datalist.eq(i+1).parent().parent().index();
                $child = $('#table tbody').children('tr:lt('+end+'):gt('+start+')');
            }else if($datalist.eq(i).parent().parent().index()==start){
                $child = $('#table tbody').children('tr:gt('+start+')'); 
            }
        }
        
        $child.toggle();
        if($child.css('display')=='none'){
            $(this).children().text('▼');
        }else{
            $(this).children().text('▲');
        }
        
    })
//售出补货改价弹框
$("a[class^='edit']").click(function(){
    $('.editPrice').show();
    var dialog = $('.editPrice .modal-dialog');
    var thisTr = $(this).parents('tr');
    var orderId = thisTr.children().last().attr('data');
    var orderPrice = thisTr.find('.orderPrice').text();
    var orderCode = thisTr.find('.orderCode').text();
    dialog.css('margin-top','150px');
    $('#orderId').val(orderId);
    dialog.find('h4').text(orderCode);
    $('#btnSubmit').attr('data','editOrderPrice');
    dialog.find('#formPrice').val(orderPrice);

    $.post('/deliver/getExpress',{id:orderId},function(res){
        var $data = res.data;
        $('#real_freight').val($data.orderPrice.real_freight);
        $('#real_pack').val($data.orderPrice.real_pack);
        $('#real_certificate').val($data.orderPrice.real_certificate);
        $('#real_other').val($data.orderPrice.real_other);
    },'json')

    if ( $(this).attr('class') == 'edit1' ) {
        $('#btnSubmit').attr('data','editOrderPrice');
        dialog.find('.body1').removeClass('none');
        dialog.find('.body2').addClass('none');
    }else if( $(this).attr('class') == 'edit2' ){
        $('#btnSubmit').attr('data','editOtherPrice');
        dialog.find('.body2').removeClass('none');
        dialog.find('.body1').addClass('none');
    }
})

//修改价格
$('#btnSubmit').bind({
    click:function(){
        $('.editPrice').hide();
        var action = $(this).attr('data');
        $.post('/deliver/'+action,$('#orderForm').serialize(),function(result){
            if (result.success == 1) {
                var thisTd = $("td[data='"+result.data[1]+"']");
                thisTd.siblings('.orderPrice').text(result.data[0]);
                $('#orderPrice').text(result.data[0]);
                alert('操作成功');
            }else if (result.success == 3) {
                alert('操作成功');
            }else if( result.success == 0 ){
                alert(result.error);
            }else if( result.success == 2 ){
                alert(result.notice);
            }
        },'json')
    }
})

</script>