<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>erp管理系统</title>

    <!-- Bootstrap -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/item.css" rel="stylesheet">
    <link href="/css/common.css" rel="stylesheet">

    <style>
    html, body {-webkit-font-smoothing: antialiased}
    #navbar-module {background-color: #1EA2D6; color: white; padding: 4px 6px 3px 6px; margin-left:0; margin-bottom:13px;}
    .form-control, .btn {-webkit-box-shadow: none; box-shadow: none}
    .navbar {border-bottom: 0px solid #f1f1f1; background-color: rgba(0, 0, 0, 0.9)}
    #div-content {padding-top: 40px}
    .div-single {margin-top: 40px;}
    .dev-sidebar {padding: 0};
    .dev-sidebar .nav {border-right: 1px solid #eee};
    .dev-sidebar .nav>li>a {color: #333;}
    .dev-sidebar .nav>li>a:link {color: #333;}
    .dev-sidebar .nav>li>a:visited {color: #333;}
    .dev-sidebar .nav>li.active>a {color: #000}

    .dev-sidebar .nav>li>ul>li {padding-left: 16px;}
    .placeholder { color: #aaa; }

    .colPicbox { overflow:hidden;}
    .col-dl-6 > dl { margin:0 auto 15px; }
    .col-dl-6 dt { position:relative; width:100%; border:1px solid #eee;}
    .col-dl-6 .col-dl-6-Img {width:136px; height:89px; display:block; }
    .col-dl-6 .col-dl-6-Img img {width:100%; height:89px;display:block;}
    .col-dl-6-editbtn { position:absolute; font-size:12px; right:5px; top:5px; color:#999;}
    .col-dl-6-editbtn:hover {color:#777;}
    .col-dl-6 dd { text-align:center; line-height:25px; height:25px; overflow:hidden;font-size:14px; color:#333;}
    .col-dl-6 dd a{color:#333;}
    .col-dl-6 dd a:hover {color:#777;}
    .col-dl-6 { padding-left:0px;}

    </style>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="/js/jquery-1.11.2.min.js"></script>  
    <script src="/upload/js/jquery.uploadify.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/js/bootstrap.min.js"></script>    
    <script src="/js/jquery.placeholder.min.js"></script>
<!--     <script src="/js/function.js"></script> -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      
    <![endif]-->
  </head>
  <body>

    <nav class="navbar navbar-inverse">
      <div class="container" style="display: block; position:relative;">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/dev">
<!--             <img src="/img/logo.png" height="24px"> -->
          </a>
          <p id="navbar-module" class="navbar-text  hidden-xs hidden-sm"><?=$this->_moduleName?></p>
        </div>        
        <div id="navbar" class="collapse navbar-collapse navbar-right">          
          <ul class="nav navbar-nav">
            <li><a href="/dev">首页</a></li>
          </ul>
        </div><!--/.nav-collapse -->
          <!--
          <div class="col-lg-6" style="position:absolute;right:0px; top:12px; width:20%;">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
              </span>
            </div>
          </div>
          -->
      </div>
    </nav>

    <div class="container" id="div-content">
      <!-- content -->
      <?=$this->_layoutContent?>
      <!-- /content -->
    </div>
    <script>
//     $('input, textarea').placeholder();
    </script>
  </body>
</html>