<!DOCTYPE HTML>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0"/>
<meta name="apple-mobile-web-app-capable" content="yes"/>
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<title>店铺首页</title>
<link href="/css/swiper.min.css" rel="stylesheet" type="text/css" />
<link href="/css/style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/js/jquery-1.9.1.js"></script>
<script type="text/javascript" src="/js/function.js"></script>
</head>
<body>
<div class="indexban">
	<img src="/images/indexban.jpg" class="indexPic" />
	<div class="indexbantxt">
		<span>大成店</span>
	</div>
</div>
<section>
	<div class="indexNav">
		<a href="#" class="active">
			<span class="Navcount iconfont01"></span>
			<span class="text">首页</span>
		</a>
		<a href="#" class="">
			<span class="Navcount iconfont02"></span>
			<span class="text">全部宝贝</span>
		</a>
		<a href="#" class="">
			<span class="Navcount iconfont03"></span>
			<span class="text">新品上架</span>
		</a>
		<a href="#" class="">
			<span class="Navcount iconfont04"></span>
			<span class="text">店铺动态</span>
		</a>
	</div>
</section>
<div class="tile_box">
	<div class="proinfotit">猜你喜欢</div>
	<div class="proinfodivbox">
		<dl class="proinfodl">
			<dt><img src="/images/m1.jpg" /></dt>
			<dd><p class="tile_title">商品详情商品详情商品详情商品详情</p></dd>
			<dd><p class="tile_price">￥43.00</p></dd>
		</dl>
		<dl class="proinfodl">
			<dt><img src="/images/m1.jpg" /></dt>
			<dd><p class="tile_title">商品详情商品详情商品详情商品详情</p></dd>
			<dd><p class="tile_price">￥43.00</p></dd>
		</dl>
		<dl class="proinfodl">
			<dt><img src="/images/m1.jpg" /></dt>
			<dd><p class="tile_title">商品详情商品详情商品详情商品详情</p></dd>
			<dd><p class="tile_price">￥43.00</p></dd>
		</dl>
	</div>
</div>
</body>
</html>