


<div class="wrapper">
    <div id="main" class="container-fluid">
<!-- BreadNav -->
            <div class="row mt10">
                <div class="col-xs-12">
                    <div class="BreadcrumbNav white">
                        <a href="">首页</a>
                        >
                        <a href="">系统管理</a>
                        >
                        <a href="">员工管理</a> 
                    </div>
                </div>
            </div>
        <div class="row mt10">
<!-- search -->            
            <div class="tabhead col-xs-12">
                <form action="" method='get'>
                        <a class="top-search btn btn-primary" href='/admin/add'>添加</a>
                        <input class="form-control top-search" style="width:150px" type="text" name="keyword" value="<?=$this->keyword?>" placeholder="名称" />
                        <button class="block top-search btn btn-primary" type="submit">搜索</button>
                </form>
                <div class="setwrap top-search">
                    <button id="setWindow" class="btn btn-primary">列设置</button>
                    <div class="set-window"></div>
                </div>
                <span class='linheit'>总数：<i class='red'><?=$this->total ?></i></span>
            </div>
        </div>
<!-- content-list -->
        <div class="row tablescroll">
            <table id="table" class="scrollTable">
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>账号</td>
                        <td>姓名</td>
                        <td>创建时间</td>
                        <td>状态</td>
                        <td>角色</td>
                        <td>类型</td>
                        <td>操作</td>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->list as $row): ?>
                        <tr>
                            <td><?=$row['id']?></td>
                            <td><?=$row['account']?></td>
                            <td><?=$row['name']?></td>
                            <td><?=date('Y-m-d H:i:s',$row['createTime'])?></td>
                            <td><?= $row['status'] >= 1 ? '禁用': '正常';?></td>
                            <td>
                                <?php foreach ($row['role'] as $v) {echo "<p>".$this->rolelist[$v['role_id']]."<p>";}?>
                            </td>
                            <td><?=$row['disName']; ?></td>
                            <td>
                                <?php if($row['status'] == 0): ?>
                                  <a href="/admin/disable/?id=<?=$row['id']?> ">禁用</a>
                                <?php else : ?>
                                  <a href="/admin/enable/?id=<?=$row['id']?> ">激活</a>
                                <?php endif; ?>
                                <a href="/admin/edit/?id=<?=$row['id']?> ">编辑</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
<!-- page -->
        <div class="row center mb10">
            <div class="pagenav">
                <div id="Pagination" class="flickr">
                    <?=$this->pagebar;?>
                </div>
                <div class="page-count">
                    <div>
                        每页显示<span id="perpage"><?=$this->perpage?></span>条
                        <ul id="pageCountSelect">
                            <li>-- 请选择 --</li>
                            <li>25</li>
                            <li>30</li>
                            <li>35</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
<!-- page-end -->
    </div>
</div>