<!DOCTYPE HTML>
<head>
<?php include(dirname(__FILE__) . '/../sys/common.phtml')?>
<title>库存</title>


<body>
<div id="preloader">
	<div id="status">
    	<p class="center-text">
			Loading the content...
            <em>Loading depends on your connection speed!</em>
        </p>
    </div>
</div>

<div class="all-elements">


   <?php include(dirname(__FILE__) . '/../sys/left_nav.phtml')?>

    <div id="content" class="page-content">

        <div class="content">
			<div class="container">
				<div class="productlist">
				    <?php if($this->list): ?>
    				    <?php foreach($this->list as $v): ?>
        					<div class="column productlistinfo">
        						<div class="prostorename">店铺名称：<?=$v['shopname'] ?></div>
        						<img src="<?=$v['img']?>" width="80" alt="img" />
        						<div class="productlistinfodiv">
        							<div class="productOpert">
        								<div class="undercarriage up" data-id="<?=$v['id'] ?>">上架</div>
        							</div>
        							<div class="productabout">
        								<span class="column-title column-name"><?=$v['name'] ?></span>
        								<span class="column-id">编号：<?=$v['id'] ?></span>
        								<em class="column-text">
        									<span class="productprice"><?=$v['price'] ?>元</span>
        								</em>
        							</div>
        						</div>
        					</div>
    					<?php endforeach; ?>
					<?php endif; ?>
				</div>
            </div>
        </div>
    </div>
</div>
</body>
</html>