<script type="text/javascript" charset="utf-8" src="/js/ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="/js/ueditor/ueditor.all.min.js"> </script>
	<div class="wrapper">
		<div id="main" class="scrollbar container-fluid">
			<div class="row mt10">
				<div class="col-xs-12">
					<div class="BreadcrumbNav white">
						<a href="">首页</a>
						>
						<a href="">详情模板管理</a>
						>
						<a href="">新建订单</a>
					</div>
					
				</div>
				
			</div>
			<form method="post" action="/copywritertemplet/edit" id="form">
            
            	<div class="row mt10">
				<div class="col-lg-2">
					<div class="leftinfo">
						<ul>
							<li class="active"><div>模块信息</div></li>
						</ul>
					</div>
				</div>
				<ul id="modul" class="col-lg-9">
				

				<li class="neworder-info modul">
						<h4 class="tit">模块信息</h4>
						<hr />
						<div class="row childpad">
						    <div class="col-lg-2 col-md-3 mb10">
							    <div class="checkbox-group">
								    <span>引入标题</span>
								</div>
							</div>
							<div class="col-sm-6 mb10">
								<?php if($this->tempList['is_title'] == '1'): ?>
				      			<?php $this->yestitle = 'checked';?>
				      			<?php else: ?>
				      			<?php $this->notitle = 'checked';?>
				      			<?php endif; ?>
						      	是
						      	<input type="radio" name="is_title" value="1" <?=$this->yestitle ?>/>
						      	否
						      	<input type="radio" name="is_title" value="0" <?=$this->notitle ?>/>
						    </div>
						</div>
						
						<div class="row childpad">
						    <div class="col-lg-2 col-md-3 mb10">
							    <div class="checkbox-group">
								    <span>引入规格</span>
								</div>
							</div>
							<div class="col-sm-6 mb10">
								<?php if($this->tempList['is_spec'] == '1'): ?>
				      			<?php $this->yesspec = 'checked';?>
				      			<?php else: ?>
				      			<?php $this->nospec = 'checked';?>
				      			<?php endif; ?>
								是
						      	<input type="radio" name="is_spec" value="1" <?=$this->yesspec ?>/>
						      	否
						      	<input type="radio" name="is_spec" value="0" <?=$this->nospec ?>/>
						    </div>
						</div>
						
						<div class="row childpad">

							<div class="col-lg-2 col-md-3 mb10">
							    <div class="checkbox-group">
								    <span>文案描述</span>
								</div>
							</div>
							<div id="" class="col-sm-9 mb10">
						      	<script id="intro" type="text/plain" name="intro" style="height:200px;"><?=htmlspecialchars_decode($this->tempList['intro']) ?></script>
						    </div>

					    </div>


<!--						<div class="row childpad text-right modul-info">
							<span onclick="deleteThisModul(this)" class="btn btn-default">删除</span>
						</div>
						<div>
							<input type="hidden" class="sort" name="sort[]" value="1">
						</div>
-->
					</li>

				</ul>
			</div>
			<input type="hidden" id="id" name="id" value="<?=$this->tempList['id']?>">
            </form>
			
			<div class="row mt10">
				<div class="col-lg-2"></div>
				<div class="col-lg-9">
					<div class="row childpad text-right modul-info">
						<span class="btn btn-no">保存</span>
						<span class="btn btn-default " onclick="goback()">返回</span>
					</div>
				</div>
			</div>
		</div>
	</div>
<!--JavaScript-->
<script type="text/javascript" src="/js/test.js/jquery.dragsort-0.5.2.js" ></script>
<script type="text/javascript">
	
	$('.btn-no').click(function(){		
		$('#form').submit();   
	})

	function goback(){
		location.href='/copywritertemplet/index';
	}

	//编辑器调用
	var ue_intro = UE.getEditor('intro',{
    	toolbars: [
               ['fullscreen', 'source', 'undo', 'redo'],
               ['selectall', 'cleardoc', 'removeformat']
            ]
        });
</script>

