<div class="form-group">
    <label for="input-title">账号</label>
    <input type="text" name="email" class="form-control" id="input-title" placeholder="账号" value="<?=$this->developer['email']?>" style="width:300px">
</div>
<div class="form-group">
    <label for="input-title">姓名</label>
    <input type="text" name="name" class="form-control" id="input-title" placeholder="名称" value="<?=$this->developer['name']?>" style="width:300px">
</div>

