


<div class="wrapper">
    <div id="main" class="container-fluid">
<!-- BreadNav -->
            <div class="row mt10">
                <div class="col-xs-12">
                    <div class="BreadcrumbNav white">
                        <a href="">首页</a>
                        >
                        <a href="">账号设置</a>
                        >
                        <a href="">账号信息</a> 
                    </div>
                </div>
            </div>
        <div class="row mt10">
<!-- search -->            
            <div class="tabhead col-xs-12">
                <div class="setwrap top-search">
                    <button id="setWindow" class="btn btn-primary">列设置</button>
                    <div class="set-window"></div>
                </div>
            </div>
        </div>
<!-- content-list -->
        <div class="row tablescroll">
            <table id="table" class="scrollTable">
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>账号</td>
                        <td>姓名</td>
                        <td>创建时间</td>
                        <td>openid</td>
                        <td>角色</td>
                        <td>操作</td>
                    </tr>
                </thead>
                <tbody>
				  		<tr>
				  			<td><?=$this->developer['id']?></td>
				  			<td><?=$this->developer['account']?></td>
				  			<td><?=$this->developer['name']?></td>
				  			<td><?=date('Y-m-d H:i:s',$this->developer['createTime'])?></td>
				  			<td><?=$this->developer['openId']?></td>
				  			<td><?=$this->rolelist[$this->developer['roleId']]; ?></td>
				  			<td><a class="btn btn-md btn-primary" href="/developer/updatepwd">修改密码</a></td>
				  		</tr>
                </tbody>
            </table>
        </div>
    </div>
</div>