<div class="col-md-4">
</div>
<div class="col-md-4 div-single">
  <?php if ($this->error): ?>
  <div class="alert alert-warning" role="alert"><?=$this->error?></div>
  <?php endif; ?>
  
  <form class="form-signin" method="POST">
      <label for="input-password" class="sr-only">password</label>
      <input type="password" name="password" id="input-password" class="form-control" placeholder="密码" required autofocus>
      <label for="input-confirm" class="sr-only">confirm password</label>
      <input type="password" name="confirm" id="input-confirm" class="form-control" placeholder="请再输入一次" required autofocus>
      <button class="btn btn-md btn-primary btn-block" type="submit">下一步</button>
  </form>
</div>
<div class="col-md-4">
</div>

<style>
.form-signin input, .form-signin button {margin: 10px 0;}
</style>