<div class="col-md-4">
</div>
<div class="col-md-4 div-single">
  <?php if ($this->error): ?>
  <div class="alert alert-warning" role="alert"><?=$this->error?></div>
  <?php endif; ?>
  
  <form class="form-signin" method="POST">
      <label for="input-name" class="sr-only">Name</label>
      <input type="text" name="name" id="input-email" class="form-control" placeholder="姓名" required autofocus>    
      <label for="inputEmail" class="sr-only">Email address</label>
      <input type="email" name="email" id="inputEmail" class="form-control" placeholder="电子邮箱" value="34145068@qq.com" required>
      <button class="btn btn-md btn-primary btn-block" type="submit">下一步</button>
  </form>
</div>
<div class="col-md-4">
</div>

<style>
.form-signin input, .form-signin button {margin: 10px 0;}
</style>