<!DOCTYPE HTML>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0"/>
<meta name="apple-mobile-web-app-capable" content="yes"/>
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<title>查看物流</title>
<link href="/css/style.css" rel="stylesheet" type="text/css" />
</head>
<body class="">
	<div class="wuliubox">
		<dl class="wuliutop overf">
			<dt><img src="/images/bg15.png" /></dt>
			<dd>物流公司：申通速递</dd>
			<dd>物流单号：STO13543573543</dd>
			<dd>热线电话：790890</dd>
		</dl>
		<div class="wuliucheng">
			<dl class="wuliudl active">
				<span class="wuliuIco"></span>
				<dt>派件已签收，签收是：杨帆</dt>
				<dd>2015.11.12 19:00</dd>
			</dl>
			<dl class="wuliudl">
				<span class="wuliuIco"></span>
				<dt>[北京市]北京站点 已发出</dt>
				<dd>2015.11.11 19:00</dd>
			</dl>
			<dl class="wuliudl">
				<span class="wuliuIco"></span>
				<dt>[北京市]已收件</dt>
				<dd>2015.11.10 23:05</dd>
			</dl>
			<dl class="wuliudl">
				<span class="wuliuIco"></span>
				<dt>卖家已发货，等待快递公司接件</dt>
				<dd>2015.11.10 19:0</dd>
			</dl>
		</div>
	</div>
</body>

<script>
//analytics
(function(i, s, o, g, r, a, m) {
	i['GoogleAnalyticsObject'] = r;
	i[r] = i[r] || function() {
		(i[r].q = i[r].q || []).push(arguments)
	}, i[r].l = 1 * new Date();
	a = s.createElement(o),
		m = s.getElementsByTagName(o)[0];
	a.async = 1;
	a.src = g;
	m.parentNode.insertBefore(a, m)
})(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

ga('create', 'UA-71370659-1', 'auto');
ga('send', 'pageview');
</script>
</html>