<!DOCTYPE HTML>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0"/>
<meta name="apple-mobile-web-app-capable" content="yes"/>
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<title>订单详情</title>
<link href="/css/swiper.min.css" rel="stylesheet" type="text/css" />
<link href="/css/style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/js/jquery-1.9.1.js"></script>
<script type="text/javascript" src="/js/function.js"></script>
</head>
<body class="graybody">
	<div class="order_detail_status overf"><img src="/images/bg10.png" /></div>
	<div class="Consigneeinfo overf">
		<dl>
			<img src="<?=$this->order['userhead'] ?>" class="fl" />
			<dd><span class="fl">收货人： <?=$this->order['uname'] ?></span><span class="fr"><?=$this->order['tel'] ?></span></dd>
			<dd>地址： <?=$htis->order['proName'].$this->order['cityName'].$this->order['areaName'].$this->order['address'] ?></dd>
		</dl>
	</div>
	<div class="detailInfo">
		<div class="detailinfoCent overf">
			<dl class="overf">
				<a href="javascript:;"><img src="<?=$this->order['goodsImg'] ?>" class="fl" /></a>
				<dt>订单号：<?=$this->order['orderCode'] ?></dt>
				<dd><span class="fl"><?=$this->order['goodsName'] ?> </span><span class="fr ordernum">×1</span></dd>
				<dd><span class="fr">￥<?=$this->order['price'] ?></span></dd>
			</dl>
		</div>
		<div class="detailinfoBot overf">
			<ul class="infoBotul fl">
				<li>优惠：－￥0.00</li>
				<li>邮费：￥<?=$this->order['freight'] ?></li>
			</ul>
			<ul class="infoBotul fr">
				<li><?=date('Y-m-d H:i:s',$this->order['createTime']) ?></li>
			</ul>
			<div class="infoBotprice fr">
				<p>合计：￥<span class="redfont"><span><?=round( $this->order['price'] ) ?></span>.00</span></p>
			</div>
		</div>
	</div>
	<div class="detailbottom">
		<span class="cuidanbtn cuidanjquery">我要催单</span>
	</div>
	
<!--催单提醒-->
<div class="window-overlay tx cuidanhidebox">
	<div class="window-overlaybg"></div>
	<div class="window">
		<dl class="cuidandl">
			<dt><img src="/images/bg05.png"  /></dt>
			<dd>请不要着急，</dd>
			<dd>物流配送还在正常范围内</dd>
		</dl>
		<span class="cuidanbottom">朕知道了</span>
	</div>
</div>
</body>

<script>
//analytics
(function(i, s, o, g, r, a, m) {
	i['GoogleAnalyticsObject'] = r;
	i[r] = i[r] || function() {
		(i[r].q = i[r].q || []).push(arguments)
	}, i[r].l = 1 * new Date();
	a = s.createElement(o),
		m = s.getElementsByTagName(o)[0];
	a.async = 1;
	a.src = g;
	m.parentNode.insertBefore(a, m)
})(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

ga('create', 'UA-71370659-1', 'auto');
ga('send', 'pageview');
</script>
</html>