<!DOCTYPE HTML>
<head>
<?php include(dirname(__FILE__) . '/../sys/common.phtml')?>
<title>登录</title>
</head>
<body>
<div class="content">
	<div class="container">
		<div class="loginbox">
			<div class="loginlogo">LOGO</div>
			<ul class="addSuppul loginul">
				<li>
					<span class="suplitit"><i class="loginIco loginuserIco"></i><span>用户名：</span></span>
					<div class="suplidiv">
						<p><input type="text" class="suppliput" id="login_account" placeholder="请输入用户名" /></p>
					</div>
				</li>
				<li>
					<span class="suplitit"><i class="loginIco loginpwdIco"></i><span>密码：</span></span>
					<div class="suplidiv">
						<p><input type="password" class="suppliput" id="login_pwd" placeholder="请输入密码" /></p>
					</div>
				</li>
			</ul>
			<input type="submit" id="user_login" class="editsavebtn button button-turqoise" value="确定">
		</div>
	</div>
</div>
</body>
</html>