<script type="text/javascript" charset="utf-8" src="/js/ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="/js/ueditor/ueditor.all.min.js"> </script>
<script type="text/javascript" charset="utf-8" src="/js/jquery.sortable.js"> </script>
<script type="text/javascript" charset="utf-8" src="/js/lightbox.js"> </script>
<link href="/css/lightbox.css" rel="stylesheet">
<div class="wrapper">
    <div id="main" class="scrollbar container-fluid">
        <div class="row mt10">
            <div class="col-xs-12">
                <div class="BreadcrumbNav white">
                    <a href="">采购管理</a>
                    >
                    <a href="">商品管理</a>
                    >
                    <a href="">编辑商品</a>
                </div>
            </div>
        </div>
        <div class="row mt10">
            <div class="col-lg-2">
                <div class="leftinfo">
                    <ul>
                        <li class="active"><div>基础信息</div></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-9 neworder-info">
                <h4 class="tit">商品信息</h4>
                <hr />
                <form method="POST" action="/goods/edit" enctype="multipart/form-data" id="form">
                    <input type="hidden" name="id" value="<?=$this->Info['id']; ?>"/>
                    <input type="hidden" name="keyword" value="<?=$this->keyword; ?>"/>
                    <input type="hidden" name="status" value="<?=$this->status; ?>"/>
                    <input type="hidden" name="page" value="<?=$this->page;?>">
                    <?php include(dirname(__FILE__) . '/form.phtml')?>
             		<div class="form-group text-right">
                    	<button type="submit" id="submitBtn" class="btn btn-primary">保存修改</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
<script type="text/javascript">
    $('#submitBtn').click(function() {
        var $shopId = $('#shopId').val();
        var $shopName = $('#goodsName').val();
        var $goodsPrice = $('#goodsPrice').val();
        /*if ( $.trim($shopId) == '') {
            alert('请选择店铺');
            return false;
        }
        if ( $.trim($shopName) == '' ) {
            alert('请填写商品名称');
            return false;
        }
        if ( $.trim($goodsPrice) == '' ) {
            alert('请填写商品价格');
            return false;
        }
        if(isNaN($goodsPrice)){
     	   alert("请填写正确的价格");
     	   return false;
     	}
*/
        $('#showBox').find('li').each(function(i){
            var type = $(this).attr('class');
            if( type == 'oldImg' ){
                $(this).find('input').attr( 'name', 'imgs['+i+']' );
            }else{
                $(this).find('input').val(i);
            }
        });

        $('#form').submit();
    })
</script>