


<div class="wrapper">
    <div id="main" class="container-fluid">
<!-- BreadNav -->
            <div class="row mt10">
                <div class="col-xs-12">
                    <div class="BreadcrumbNav white">
                        <a href="">首页</a>
                        >
                        <a href="">角色管理</a>
                        >
                        <a href="">角色列表</a> 
                    </div>
                </div>
            </div>
        <div class="row mt10">
<!-- search -->            
            <div class="tabhead col-xs-12">
                <a class="btn btn-uppercase btn-primary" id="new" href="/role/adduser?id=<?=$this->id?>" >添加用户</a>
            </div>
        </div>
<!-- content-list -->
        <div class="row tablescroll">
            <table id="table">
                <thead>
                    <tr >
                      <td>ID</td>
                      <td>邮箱</td>
                      <td>名称</td>
                      <td>操作</td>
                    </tr>
                </thead>
                <?php foreach ($this->list as $row): ?>
                  <tr >
                      <td scope="row"><?=$row['id']?></td>
                      <td><?=$row['email']?></td>
                      <td><?=$row['name']?></td>
                      <td>
                      <a href="/role/deleterole/?id=<?=$row['id']?>&rid=<?=$this->id?>"><span class="label label label-info">删除</span></a>
                      </td>
                  </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>
