<div class="wrapper">
    <div id="main" class="scrollbar container-fluid">
        <div class="row mt10">
            <div class="col-xs-12">
                <div class="BreadcrumbNav white">
                    <a href="">首页</a>
                    >
                    <a href="">角色管理</a>
                    >
                    <a href="">编辑角色</a>
                </div>
            </div>
        </div>
        <form method="POST" action="/role/edit" id="form">
        <INPUT type="hidden" name="id" value="<?=$this->id?>">
        <?php include(dirname(__FILE__) . '/form.phtml')?>
        <div class="row mt10 mb50 neworder-btn">
            <div class="col-lg-2"></div>
            <div class="col-lg-9">
                <button type="button" class="btn btn-primary" id="submitBtn">确认</button>
            </div>
        </div>
        </form>
    </div>
</div>
<script>
$('#submitBtn').click(function() {
    var $name = $('#input-title').val();
    if ( $.trim($name) == '') {
        alert('请填写姓名');
        return false;
    }
    $('#form').submit();
})
</script>