


<div class="wrapper">
    <div id="main" class="container-fluid">
<!-- BreadNav -->
            <div class="row mt10">
                <div class="col-xs-12">
                    <div class="BreadcrumbNav white">
                        <a href="">首页</a>
                        >
                        <a href="">系统管理</a>
                        >
                        <a href="">角色管理</a> 
                    </div>
                </div>
            </div>
        <div class="row mt10">
<!-- search -->            
            <div class="tabhead col-xs-12">
                <a class="top-search btn btn-primary" href='/role/add'>添加</a>
                <div class="setwrap top-search">
                    <button id="setWindow" class="btn btn-primary">列设置</button>
                    <div class="set-window"></div>
                </div>
            </div>
        </div>
<!-- content-list -->
        <div class="row tablescroll">
            <table id="table" class="scrollTable nodeTable">
                <!-- <thead>
                    <tr>
                        <td>ID</td>
                        <td>角色名称</td>
                        <td>排序</td>
                        <td>操作</td>
                    </tr>
                </thead> -->
                <tbody>
                    <?php foreach ($this->list as $key => $row): ?>
                    <tr roleId="<?=$row['id']?>" class="level1" index="<?=$key?>">
                        <td scope="row"><?=$row['id']?></td>
                        <td><?=$row['name']?></td>
                        <td><?=$row['sort']?></td>
                        <td>
                        <a href="/role/developer/?id=<?=$row['id']?>"><span class="label label label-info">用户列表</span></a>
                        <a href="/role/edit/?id=<?=$row['id']?>"><span class="label label label-info">编辑</span></a>
                        <a href="/role/delete/?id=<?=$row['id']?>"><span class="label label label-info">删除</span></a>
                        </td>
                    </tr>
                    <?php if($row['son']) :?> 
                    <tr class="none" roleId="<?=$row2['id']?>" pid="<?=$row['id']?>">
                        <td colspan="20">
                            <table class="table">   
                        <?php foreach ($row['son'] as $row2) :?>
                            <tr class="none level2" roleId="<?=$row2['id']?>" pid="<?=$row['id']?>">
                                <td scope="row"><?=$row2['id']?></td>
                                <td>--/<?=$row2['name']?></td>
                                <td><?=$row2['sort']?></td>
                                <td>
                                <a href="/role/developer/?id=<?=$row2['id']?>"><span class="label label label-info">用户列表</span></a>
                                <a href="/role/edit/?id=<?=$row2['id']?>"><span class="label label label-info">编辑</span></a>
                                <a href="/role/delete/?id=<?=$row2['id']?>"><span class="label label label-info">删除</span></a>
                                </td>
                            </tr>
                            <?php if($row2['son']) :?>
                            <tr class="none" pid="<?=$row2['id']?>">
                                <td colspan="20">
                                    <table class="table">
                                        <?php foreach ($row2['son'] as $row3) :?>
                                            <tr class="none level3" pid="<?=$row2['id']?>">
                                              <td scope="row"><?=$row3['id']?></td>
                                              <td>--/--/<?=$row3['name']?></td>
                                              <td><?=$row3['sort']?></td>
                                              <td>
                                              <a href="/role/developer/?id=<?=$row3['id']?>"><span class="label label label-info">用户列表</span></a>
                                              <a href="/role/edit/?id=<?=$row3['id']?>"><span class="label label label-info">编辑</span></a>
                                              <a href="/role/delete/?id=<?=$row3['id']?>"><span class="label label label-info">删除</span></a>
                                              </td>
                                            </tr>
                                        <?php endforeach;?>
                                    </table>
                                </td>
                            </tr>
                            <?php endif;?>
                        <?php endforeach;?>
                            </table>
                        </td>
                    </tr>
                    <?php endif;?>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    var roleFlag = [];
    for (var i = 0; i < $('tbody tr.level1').length; i++) {
        roleFlag[i] = 0;
    }
    $('tbody tr.level1').click(function(){
        var roleId = $(this).attr('roleId');
        var index = $(this).attr('index');
        if (roleFlag[index] == 0) {
            $("tr[pid='"+roleId+"']").show();
            roleFlag[index] = 1;
        }else{
            $("tr[pid='"+roleId+"']").hide();
            roleFlag[index] = 0;
        }
    })
    $('tbody tr.level2').click(function(){
        var roleId = $(this).attr('roleId');
        $("tr[pid='"+roleId+"']").toggle('none');
    })

    $('table a').click(function(e){
        e.stopPropagation();
    })
</script>