<div class="row mt10">
    <div class="col-lg-2">
        <div class="leftinfo">
            <ul>
                <li class="active"><div>添加-供货商</div></li>
            </ul>
        </div>
    </div>
    <div class="col-lg-9 neworder-info">
        <h4 class="tit">供应商</h4>
        <hr />
        <div class="row childpad">
            <label class="col-lg-1 col-md-2 control-label">昵称</label>
            <div class="col-sm-4">
                <input type="text" name="name" id="name" class="form-control" value="<?=$this->info['name'] ?>" placeholder="供应商昵称"/>
            </div>
        </div>
        <div class="row childpad">
            <label class="col-lg-1 col-md-2 control-label">手机号</label>
            <div class="col-sm-4">
                <input type="text" id="uphone" class="form-control" name="uphone"  value="<?=$this->info['account'] ?>" placeholder="手机号" />
            </div>
        </div>
        <div class="row childpad">
            <label class="col-lg-1 col-md-2 control-label">密码</label>
            <div class="col-sm-4">
                <input type="password" class="form-control" id="upwd" name="upwd" class="userpwd" placeholder="登录密码"/>
            </div>
        </div>
    </div>
</div>