


<div class="wrapper">
    <div id="main" class="container-fluid">
<!-- BreadNav -->
            <div class="row mt10">
                <div class="col-xs-12">
                    <div class="BreadcrumbNav white">
                        <a href="">首页</a>
                        >
                        <a href="">采购管理</a>
                        >
                        <a href="">供应商管理</a> 
                    </div>
                </div>
            </div>
        <div class="row mt10">
<!-- search -->            
            <div class="tabhead col-xs-12">
                <form action="" method='get'>
                        <a class="top-search btn btn-primary" href='/supplier/add'>添加</a>
                        <input class="form-control top-search" style="width:150px" type="text" name="keyword" value="<?=$this->keyword?>" placeholder="姓名，账号" />
                        <button class="block top-search btn btn-primary" type="submit">搜索</button>
                </form>
                <div class="setwrap top-search">
                    <button id="setWindow" class="btn btn-primary">列设置</button>
                    <div class="set-window"></div>
                </div>
                <span class='linheit'>总数：<i class='red'><?=$this->total ?></i></span>
            </div>
        </div>
<!-- content-list -->
        <div class="row tablescroll">
            <table id="table" class="scrollTable">
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>姓名</td>
                        <td>账号</td>
                        <td>微信号</td>
                        <td>性别</td>
                        <td>状态</td>
                        <td>创建时间</td>
                        <td>操作</td>
                    </tr>
                </thead>
                <tbody>
                    <?php if($this->list):?>
                    <?php foreach ($this->list as $row): ?>
                        <tr>
                            <td><?=$row['id']?></td>
                            <td><?=$row['name']?></td>
                            <td><?=$row['account']?></td>
                            <td><?=$row['weixin']?></td>
                            <td><?php if($row['sex'] == 1): ?>男<?php else: ?>女<?php endif; ?></td>
                            <td><?php if($row['status'] == 1): ?>禁用<?php else: ?>正常<?php endif; ?></td>
                            <td><?=date('Y-m-d H:i:s',$row['createTime'])?></td>
                            <td>
                                <!-- <div class="btn-group btn-search">
                                    <span class="btn btn-default dropdown-toggle">请选择<i class="caret"></i></span>
                                    <ul class="batch-menu">
                                        <?php if($row['status'] == 1): ?>
                                              <a href="/supplier/enable/?id=<?=$row['id']?>"><li><img src="/img/jinyong.png">启用</li></a>
                                        <?php else: ?>
                                              <a href="/supplier/disable/?id=<?=$row['id']?>"><li><img src="/img/jinyong.png">禁用</li></a>
                                        <?php endif; ?>
                                        <a href="/supplier/view/?id=<?=$row['id']?>"><li><img src="/img/xiangqing.png">查看</li></a>
                                        <a href="/supplier/edit/?id=<?=$row['id']?>"><li><img src="/img/bianji.png">编辑</li></a>
                                    </ul>
                                </div> -->
                                <div class="order_menu menu-btn3">
                                <?php if($row['status'] == 1): ?>  
                                    <a href="/supplier/enable/?id=<?=$row['id']?>"><span class="btn-orderDetails btn btn-default"><img src="/img/qiyong.png"><i>启用</i></span></a>
                                <?php else: ?>
                                    <a href="/supplier/disable/?id=<?=$row['id']?>"><span class="btn-orderDetails btn btn-default"><img src="/img/jinyong.png"><i>禁用</i></span></a>
                                <?php endif; ?>
                                    <a href="/supplier/view/?id=<?=$row['id']?>"><span class="btn-center btn btn-default"><img src="/img/xiangqing.png"><i>查看</i></span></a>
                                    <div class="btn-group btn-search">
                                        <a href="/supplier/edit/?id=<?=$row['id']?>"><span data="<?=$row['id']?>" class="btn btn-default"><img src="/img/bianji.png">编辑</span></a>
                                        
                                    </div>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    <?php endif;?>
                </tbody>
            </table>
        </div>
<!-- page -->
        <div class="row center mb10">
            <div class="pagenav">
                <div id="Pagination" class="flickr">
                    <?=$this->pagebar;?>
                </div>
                <div class="page-count">
                    <div>
                        每页显示<span id="perpage"><?=$this->perpage?></span>条
                        <ul id="pageCountSelect">
                            <li>-- 请选择 --</li>
                            <li>25</li>
                            <li>30</li>
                            <li>35</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
<!-- page-end -->
    </div>
</div>