<script type="text/javascript" src="/js/test.js/jedate.min.js" ></script>
<div class="wrapper">
	<div id="main" class="scrollbar container-fluid">
		<div class="row mt10">
			<div class="col-xs-12">
				<div class="BreadcrumbNav white">
					<a href="">首页</a>
					>
					<a href="">财务管理</a>
					>
					<a href="">结算申请</a>
				</div>
			</div>
		</div>
		
		<div class="row mt10">
			<div class="col-lg-2">
				<div class="leftinfo">
					<ul>
						<li class="active"><div>结算申请列表</div></li>
						<li><div>新增结算申请</div></li>
					</ul>
				</div>
			</div>

			
			<div class="col-lg-9 neworder-info tablescroll">
				<div class="row mt10">
				    <div class="tabhead col-xs-12">
		                <form action="" method='get'>
	                        <input class="form-control top-search" style="width:150px" type="text" name="keyword" value="<?=$this->keyword?>" placeholder="供应商名称" />
	                        <!-- <span class="block linheit top-search">状态：</span>
	                        <select name="status" class="block form-control top-search">
	                            <option value="0" <?php if($this->status == 0) echo "selected = 'selected'" ?> >全部</option>
	                            <option value="1" <?php if($this->status == 1) echo "selected = 'selected'" ?> >等待审核</option>
	                            <option value="2" <?php if($this->status == 2) echo "selected = 'selected'" ?> >审核通过</option>
	                            <option value="3" <?php if($this->status == 3) echo "selected = 'selected'" ?> >审核异常</option>
	                            <option value="4" <?php if($this->status == 4) echo "selected = 'selected'" ?> >驳回申请</option>
	                        </select> -->
	                        <input type="hidden" name="status" value="<?=$this->status?>">
                            <span class="block linheit top-search">申请时间：</span>
                            <input name="starttime" id="indate4" class="top-search form-control" type="text" placeholder="请输入日期" value="<?=$this->starttime?>" readonly/>
                            <span class="block linheit top-search"> - </span>
                            <input name="endtime" id="indate5" class="top-search form-control" type="text"  placeholder="请输入日期" value="<?=$this->endtime?>" readonly/>
	                        <button class="block top-search btn btn-primary" type="submit">搜索</button>
		                	<span class="block top-search btn btn-primary" id="exportExcel">批量导出</span>
		                </form>
		            </div>
				</div>
				<div class="row mt10 finance-ul">
                    <ul>
                        <li class="finance-btn <?php if($this->status == 4) echo 'active' ?>"><a href="/account/index?status=4&keyword=<?=$this->keyword?>&starttime=<?=$this->starttime?>&endtime=<?=$this->endtime?>"><p>系统提交<span><?=$this->total4?></span></p></a></li>
                        <li class="finance-btn <?php if($this->status == 0) echo 'active' ?>"><a href="/account/index?status=0&keyword=<?=$this->keyword?>&starttime=<?=$this->starttime?>&endtime=<?=$this->endtime?>"><p>等待审核<span><?=$this->total0?></span></p></a></li>
                        <li class="finance-btn <?php if($this->status == 1) echo 'active' ?>"><a href="/account/index?status=1&keyword=<?=$this->keyword?>&starttime=<?=$this->starttime?>&endtime=<?=$this->endtime?>"><p>审核通过<span><?=$this->total1?></span></p></a></li>
                        <li class="finance-btn <?php if($this->status == 2) echo 'active' ?>"><a href="/account/index?status=2&keyword=<?=$this->keyword?>&starttime=<?=$this->starttime?>&endtime=<?=$this->endtime?>"><p>审核异常<span><?=$this->total2?></span></p></a></li>
                        <li class="finance-btn <?php if($this->status == 3) echo 'active' ?>"><a href="/account/index?status=3&keyword=<?=$this->keyword?>&starttime=<?=$this->starttime?>&endtime=<?=$this->endtime?>"><p>驳回申请<span><?=$this->total3?></span></p></a></li>
                        <div class="clearfix"></div>
                    </ul>
	                
	            </div>

				<?php if ( in_array( 1,$this->_developer['role'] ) || $this->_developer['id'] == 9 || $this->_developer['id'] == 13 ) : ?>
					<div class='posre'>
					<table  class="table mt10 scrollTable">
						<thead>
							<tr>
								<td>标记</td>
								<td>申请时间</td>
								<td>供应商名称</td>
								<td>分组类别</td>
								<td>申请人</td>
								<td>应付小计</td>
								<td>预计付款时间</td>
								<td>备注</td>
								<td>操作</td>
							</tr>
						</thead>
						<tbody>
							<?php foreach ($this->list as $row ): ?>
							<tr data="<?=$row['id']?>">
								<td>
									<?php if ($row['audit_status'] == 2) {echo "<i>!</i>";}else{echo "";} ?>
								</td>
								<td><p><?=date('Y-m-d H:i:s',$row['createTime'])?></p></td>
								<td><p><?=$row['shopName'];?></p></td>
								<td>
									<?php if($row['category'] == 1) echo "只有一个";
									elseif($row['category'] == 2) echo "绣花张";
									elseif($row['category'] == 3) echo "悦榕阁";?>
								</td>
								<td><?=$row['devName'];?></td>
								<td><?=$row['total'];?></td>
								<td><?=$row['expectTime'];?></td>
								<td class="note"><?=$row['note'];?></td>
								<td data="<?=$row['id']?>">
                                    <div class="order_menu">
                                    <span toggle='yes' data="<?=$row['id']?>" class="fl btn-orderDetails btn btn-default"><img src="/img/eye.png"/><span>预览</span></span>
                                        <div class="btn-group btn-search fl">
                                                <?php if( $this->orderType == 4 && $this->isBuyer == 0 ):?>
                                                    <span class="btn btn-default buyerShow">订单采购</span>
                                                <?php else:?>
                                                    <span class="btn btn-default dropdown-toggle">请选择<span class="caret"></span></span>
                                                    <ul class="batch-menu">
														<a class="del"><li><img src="/img/shanchu.png">删除</li></a>
														<a class="edit1"><li><img src="/img/xiugai.png">修改备注</li></a>
														<?php if ( $row['audit_status'] == 4 ) :?>
															<a class="confirm"><li><img src="/img/bianji.png">确认申请</li></a>
														<?php endif;?>
                                                    </ul>
                                                <?php endif;?>
                                        </div>
                                    </div>
                                </td>
							</tr>
							<?php endforeach; ?>
							<tr class="none" id="orderDetail">
								<td colspan="20">
									<div class="row">
										<input id="hiddenId" type="hidden" name="id" />
										<table class="table table4">
											<thead>
												<tr>
													<td>日期</td>
													<td>订单编号</td>
													<td>商品名称</td>
													<td>SKU编码</td>
													<td>数量</td>
													<td>进货价格</td>
													<td>运费结算</td>
													<td>包装结算</td>
													<td>证书结算</td>
													<td>其他费用</td>
													<td>应付金额</td>
													<td>状态</td>
												</tr>
											</thead>
											<tbody>
												
											</tbody>
										</table>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
					</div>
				<?php endif;?>
			</div>
			<div class="col-lg-9 neworder-info none">
				<h4 class="tit">结算申请查询</h4>
				<hr />
				<div class="row childpad mt10">
				    <div class="col-sm-4 col-xs-12">
				      	<div class="inp-tit">供应商编号</div>
						<div class="inp-inp">
							<div><input id="scode" type="text" class="form-control" /></div>
						</div>

				    </div>
				    <label class="col-md-2 col-lg-1 col-xs-12 control-label">业务日期</label>
				    <div class="col-sm-7 col-xs-12">
				      	<input id="indate" class="form-control width50" type="text" placeholder="请输入日期" readonly /><span class="linheit"> - </span><input id="indate2" class="form-control width50" type="text"  placeholder="请输入日期" readonly/>
				    </div>
				</div>
				<div class="row clearing-btn mb10">
					<button id="search" class="btn btn-primary">查询申请内容</button>
				</div>
			</div>
		</div>

				
		<form id="form" method="POST" action="/account/add" class="none">
			<div class="row mt10">
				<div class="col-lg-2"></div>
				<div class="col-lg-9 neworder-info">
					<table id="table" class="none table3">
						<thead>
							<tr>
								<td class="tdfirst"><input id="checkBox" type="checkbox" /></td>
								<td>状态</td>
								<td>日期</td>
								<td>订单编号</td>
								<td>商品名称</td>
								<td>SKU编码</td>
								<td>数量</td>
								<td>进货价格</td>
								<td>运费结算</td>
								<td>包装结算</td>
								<td>证书结算</td>
								<td>其他费用</td>
								<!--<td>实付单价</td>-->
								<td>应付金额</td>
								<!--<td>实付金额</td>-->
							</tr>
						</thead>
						<tbody>
							
						</tbody>
					</table>
				</div>
			</div>
			<div class="row mt10">
				<div class="col-lg-2"></div>
				<div class="col-lg-9 neworder-info">
					<h4 class="tit">结算申请内容</h4>
					<hr />
					<div class="row childpad mt10">
						<input type="hidden" id="shopId" name="shopId" value="">
					    <div class="col-md-4 col-xs-12">
					      	<div class="inp-tit">供应商名称</div>
							<div class="inp-inp">
								<div><input id="shopName" type="text" class="form-control" readonly="" /></div>
							</div>
					    </div>

					    <div class="col-md-4 col-xs-12">
					      	<div class="inp-tit">分组类别</div>
							<div class="inp-inp">
								<div>
									<select id="category" name="category" class="form-control" disabled="">
										<option></option>
										<option value="1" >只有一个</option>
										<option value="2" >绣花张</option>
										<option value="3" >悦榕阁</option>
							      	</select>
						      	</div>
							</div>
					    </div>
						    
					    <div class="col-md-4 col-xs-12">
					      	<div class="inp-tit">申请人</div>
							<div class="inp-inp">
								<div>
									<input value="<?=$this->_developer['name']?>" type="text" class="form-control" readonly="" />
						      	</div>
							</div>
					    </div>
					</div>
					<div class="row childpad mt10">
					    <div class="col-md-4 col-xs-12">
					      	<div class="inp-tit">应付小计</div>
							<div class="inp-inp">
								<div>
									<input id="total" name="total" type="text" class="form-control" readonly="" />
						      	</div>
							</div>
					    </div>
					    <div class="col-md-4 col-xs-12">
					      	<div class="inp-tit">类型</div>
							<div class="inp-inp">
								<div>
									<input id="real_total"value="供货商结算" type="text" class="form-control" readonly="" />
						      	</div>
							</div>
					    </div>
					    <div class="col-md-4 col-xs-12">
					      	<div class="inp-tit">预计付款时间</div>
							<div class="inp-inp">
								<div>
									<input id="indate3" name="expectTime" class="form-control" type="text"  placeholder="请输入日期" readonly/>
						      	</div>
							</div>
					    </div>
					</div>
					<div class="row childpad mt10">
					    <div class="col-md-4 col-xs-12">
					      	<div class="inp-tit">备注</div>
							<div class="inp-inp">
								<div>
									<input type="text" name="note" class="form-control" />
						      	</div>
							</div>
					    </div>
					</div>
					<div class="row clearing-btn mb10">
						<span class="btn btn-primary"  id="submitBtn" >提交申请</span>
					</div>
				</div>
			</div>
		</form>
		<!-- 修改备注窗口 -->
		<div class="modal noteWindow">
		    <div class="modal-dialog">
		        <div class="modal-content">
		            <div class="modal-header">
		                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		                <h4 class="modal-title">请输入备注</h4>
		            </div>
		            <form method="post" id="accountForm">
		                <input type="hidden" name="accountId" id="accountId">
		                <div class="modal-body body1">
		                    <div class="col-xs-6 col-xs-offset-2">
		                        <div class="inp-tit text-center">备注</div>
		                        <div class="inp-inp">
		                            <div>
		                                <input class="form-control" type="text" id="editNote" name="editNote" />
		                            </div>
		                        </div>
		                    </div>
		                    <div class="clearfix"></div>
		                </div>
		                <div class="modal-footer">
		                    <span class="btn btn-default" data-dismiss="modal">取消</span>
		                    <button id="btnSubmit" type="button" class="btn btn-primary" data="" >确定</button>
		                </div>
		            </form>
		        </div>
		    </div>
		</div>

	</div>
</div>

<script type="text/javascript">
$('#exportExcel').bind({
    click:function(){
        var $form = $(this).parent();
        $form.attr('action','/account/exportExcel');
        $form.submit();
        $form.attr('action','');
        return false;
    }
});
//日期
jeDate({
    dateCell:"#indate4",//isinitVal:true,
    format:"YYYY-MM-DD",
    isTime:false, //isClear:false,
    minDate:"1970-1-1 00:00:00"
})
jeDate({
    dateCell:"#indate5",//isinitVal:true,
    format:"YYYY-MM-DD",
    isTime:false, //isClear:false,
    minDate:"1970-1-1 00:00:00"
})
$('#submitBtn').click(function() {
	if (confirm('确定要提交吗？') ) {
		var $total = $('#total').val();
	    if ( $.trim($total) == '' || $total == 0) {
	        alert('请选择订单');
	        return false;
	    }
	    var $indate3 = $('#indate3').val();
	    if ( $.trim($indate3) == '') {
	        alert('请选择预付时间');
	        return false;
	    }
    	$('#form').submit();
	}
})
$('#search').click(function(){
	var scode = $('#scode').val();
	var start = $('#indate').val();
	var end   = $('#indate2').val();
	if ( $.trim(scode) == '') {
		alert('请填写供应商编号');
		return false;
	};
	if ( $.trim(start) == '') {
		alert('请填写开始时间');
		return false;
	};
	if ( $.trim(end) == '') {
		alert('请填写结束时间');
		return false;
	};
	$.post('/account/search',
		{'scode':scode,'start':start,'end':end},
		function(result){
		// console.log(result)
		if (result.success == 1) {
			$('#table tbody').empty();
			$('#table').show();
			for (var i = 0; i < result.data.length ; i++) {
				var status = '';
				if (result.data[i].account_status == 3) {
					status = '<td><i>!</i></td>';
				}else{
					status = '<td></td>';
				}
				var $total = ((result.data[i].number*result.data[i].purchPrice)+parseFloat(result.data[i].real_certificate)+parseFloat(result.data[i].real_pack)+parseFloat(result.data[i].real_other)+parseFloat(result.data[i].real_freight)).toFixed(2);
				var tr = '<tr data="'+result.data[i].id+'"><td><input name="orderId['+i+']" class="checkbox" value="'+result.data[i].id+'" type="checkbox" /></td>'+status+'<td>'+result.data[i].payTime+'</td><td>'+result.data[i].orderCode+'</td><td>'+result.data[i].name+'</td><td>'+result.data[i].code+'</td><td>'+result.data[i].number+'</td><td>'+result.data[i].purchPrice+'</td><td>'+result.data[i].real_freight+'</td><td>'+result.data[i].real_pack+'</td><td>'+result.data[i].real_certificate+'</td><td>'+result.data[i].real_other+'</td><td>'+$total+'</td></tr>';
				$('#table tbody').append($(tr));
			};
			//<td><input type="text" class="real_price" value="'+result.data[i].purchPrice+'" /></td>实付单价
			//<td>'+(result.data[i].number*result.data[i].purchPrice).toFixed(2)+'</td>实付金额
			$('#shopId').val(result.data[0].shopId);
			$('#shopName').val(result.data[0].shopName);
			//改变实付单价
			var $real_price = $('.real_price');
			var $tr = $('#table tbody tr');
			// $real_price.bind('input propertychange', function() {
			// 	var real_total = 0;
			// 	for (var i = 0; i < result.data.length; i++) {
			// 		$real_total = $real_price.eq(i).val()*result.data[i].number;
			// 		$tr.eq(i).find(':last').html(($real_total).toFixed(2));
			// 		if ($tr.find('input').eq(i).prop('checked')==true) {
			// 			real_total += $real_total;
			// 		}
			// 	};
			// 	$('#real_total').val((real_total).toFixed(2));
			// });
			//单选框
			$('.checkbox').bind('change',function(){
				var total = 0;
				//var real_total = 0;
				for (var j = 0; j < result.data.length; j++) {
					if ($("[data='"+result.data[j].id+"']").find('input').prop('checked')==true) {
						var realprice = parseFloat($tr.eq(j).find(':last').html());
						//var real_totalprice = $tr.eq(j).find(':last').html();
						total += realprice;
						//real_total += parseFloat(real_totalprice);
					}
				}
				$('#total').val((total).toFixed(2));
				//$('#real_total').val((real_total).toFixed(2));
			})
			//内容
			var opt = $('#category').find('option');
			for (var i = 0; i < opt.length; i++) {
				if (result.data[0].category == opt.eq(i).val()){
					opt.eq(i).attr('selected',true)
				}
			};
			$("#checkBox").prop({"checked":false});
			$('#total').val(0);
			checkAll = false;
		}else if( result.success == 0 ){
			$('#table').hide();
			$('#shopName').val('');
			alert("没有数据");
		}else if( result.success == 2 ){
			alert(result.notice);
		}
	},'json')
})


//全选
var checkAll = false;
    $("#checkBox").click(function(){
    	var total = 0;
    	//var real_total = 0;
        if(!checkAll){
            $("#table").find("tr input").prop({"checked":true});
            checkAll = true;
            var tr = $("#table tbody").find('tr');
            for (var i = 0; i< tr.length; i++){
            	total += parseFloat(tr.eq(i).find(':last').html());
            	//real_total += parseFloat(tr.eq(i).find(':last').html());
            }
        }else if(checkAll) {
            checkAll = false;
            $("#table").find("tr input").prop({"checked":false});
            total = 0;
            //real_total = 0;
        }
        $('#total').val((total).toFixed(2))
        //$('#real_total').val((real_total).toFixed(2))
    })
//日期
jeDate({
	dateCell:"#indate",//isinitVal:true,
	format:"YYYY-MM-DD",
	isTime:false, //isClear:false,
})
jeDate({
	dateCell:"#indate2",//isinitVal:true,
	format:"YYYY-MM-DD",
	isTime:false, //isClear:false,
})
jeDate({
	dateCell:"#indate3",//isinitVal:true,
	format:"YYYY-MM-DD",
	isTime:false, //isClear:false,
})
	//信息切换
	var $liList = $('.leftinfo ul li');
	var $info = $('.leftinfo').parent().siblings();
	$liList.click(function(){
		if($(this).index()==1){
			$('#form').show();
		}else{
			$('#form').hide();
		}
		$(this).addClass('active').siblings().removeClass('active');
		for(var i=0;i<$info.length;i++){
			$info.eq(i).addClass('none');
		}
		$info.eq($(this).index()).removeClass('none');
	})
	//详情点击
	var $btn = $('.table tbody').find('.btn-orderDetails');
	$btn.bind('click',function(){
		showOrderInfo($(this));
		var id = $(this).parents('td').attr('data');
		$.post('/account/detail',{'id':id},function(result){
			if (result.success == 1) {
				var orderTr = '';
				var status = '';
				for (var i = 0; i < result.data.length; i++) {
					if (result.data[i].account_status == 1) {
						status = '等待确认';
					}else if(result.data[i].account_status == 2) {
						status = '确认完成';
					}else if(result.data[i].account_status == 3) {
						status = '驳回申请';
					}

					var $total = ((result.data[i].number*result.data[i].purchPrice)+parseFloat(result.data[i].real_certificate)+parseFloat(result.data[i].real_pack)+parseFloat(result.data[i].real_other)+parseFloat(result.data[i].real_freight)).toFixed(2);
					orderTr += '<tr><td>'+result.data[i].payTime+'</td><td>'+result.data[i].orderCode+'</td><td>'+result.data[i].name+'</td><td>'+result.data[i].code+'</td><td>'+result.data[i].number+'</td><td>'+result.data[i].purchPrice+'</td><td>'+result.data[i].real_freight+'</td><td>'+result.data[i].real_pack+'</td><td>'+result.data[i].real_certificate+'</td><td>'+result.data[i].real_other+'</td><td>'+$total+'</td><td>'+status+'</td></tr>';
				};
				$('.table4 tbody').html(orderTr);
			}else if( result.success == 0 ){
				$('.table4 tbody').html('');
			}else if( result.success == 2 ){
				alert(result.notice);
			};
		},'json')
	})
	$('.del').bind({
		click:function(){
			if (confirm('确定要删除吗？') ) {
				var id = $(this).parents('tr').attr('data');
				var $thisTr = $(this).parents('tr');
				var $orderDetail = $(this).parents('tbody').find('#orderDetail');
				$.post('/account/del',{'id':id},function(result){
					if (result.success == 1) {
						$thisTr.hide();
						$orderDetail.hide();
						alert("成功");
					}else{
						alert(result.error);
					}
				},'json')
			}
		}
	})
	$('.confirm').bind({
		click:function(){
			if ( confirm( '确定要提交申请吗？' ) ){
				var id = $(this).parents('td').attr('data');
				var $thisTr = $(this).parents('tr');
				var $orderDetail = $(this).parents('tbody').find('#orderDetail');
				$.post('/account/editStatus',{'id':id},function(result){
					if ( result.success == 1 ) {
						$thisTr.hide();
						$orderDetail.hide();
						alert("成功");
					}else if ( result.success == 0 ){
						alert( result.error );
					}else if ( result.success == 2 ){
						laert( result.notice );
					}
				},'json')
			}
		}
	})
	$("a[class^='edit']").bind({
		click:function(){
			$('.noteWindow').show();
		    var thisTr = $(this).parents('tr');
		    var accountId = thisTr.children().last().attr('data');
		    $('#accountId').val(accountId);

		    if ( $(this).attr('class') == 'edit1' ) {
		        $('#btnSubmit').attr('data','editNote');
		    }
		}
	})
    $('.modal').find('.close').click(function(){
        $('.modal').hide();
    })
    $('.modal').find('.btn-default').click(function(){
        $('.modal').hide();
    })
    //修改备注
	$('#btnSubmit').bind({
	    click:function(){
	        $('.noteWindow').hide();
	        var action = $(this).attr('data');
	        $.post('/account/'+action,$('#accountForm').serialize(),function(result){
	            if (result.success == 1) {
	            	var noteTd = $("td[data='"+result.data[0]+"']").prev();
	            	noteTd.html(result.data[1]);
	                alert('操作成功');
	            }else if( result.success == 0 ){
	                alert(result.error);
	            }else if( result.success == 2 ){
	                alert(result.notice);
	            }
	        },'json')
	    }
	})
</script>