<script type="text/javascript" src="../upload/js/jquery-1.10.0.min.js"></script>
<script type="text/javascript" src="../upload/js/jquery.uploadify.min.js"></script>
<div class="wrapper">
    <div id="main" class="scrollbar container-fluid">
        <div class="row mt10">
            <div class="col-xs-12">
                <div class="BreadcrumbNav white">
                    <a href="">首页</a>
                    >
                    <a href="">采购管理</a>
                    >
                    <a href="">店铺管理</a>
                </div>
            </div>
        </div>
        <form id="upload" action="/import/index" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="uid" />
            <div class="row mt10">
                <div class="col-md-5">
                    <table id="table"> 
                        <tr>
                            <td>上传商品文件</td>
                            <td><a href="javascript:;"><input id="file_upload_excel" name="file_upload" type="file" ></a> </td>
                            <!--    <td><input id="file_upload_img" name="file_upload" type="file" ></td> -->
                            <td>
                                <div class="btn-group open">
                                    <ul class="dropdown-menu" id="dropdown" style="display:none">
                                    </ul>
                                </div>
                            </td>
                            <ul>
                                <li id="imageArea"></li>
                            </ul>
                        </tr>
                        <tr>
                            <td>上传商品图片</td>
                            <td><a href="javascript:;"><input id="uploadimg" type="file" class="upload"></a></td>
                            <td></td>
                            <ul>
                                <li id="goodsimg"></li>
                            </ul>
                        </tr>
                        <tr>
                            <td>图片上传成功数：</td>
                            <td class="successNum text-left">0</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>图片上传失败数：</td>
                            <td class="failNum text-left">0</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>失败图片名：</td>
                            <td class="failNum"></td>
                            <td></td>
                        </tr>
                    </table>
                </div>
            </div>
        <div id="excel_file_queue"></div>
        </form>
    </div>
</div>
<script type="text/javascript">
    $(function() {
        $('#file_upload_excel').uploadify({
            'multi'    : false,
            'swf'      : '../upload/uploadify.swf',
            'uploader' : '../upload/uploadify.php',
            'fileSizeLimit': '5120KB',
            'buttonText': '<div align="center">选择商品excel</div>',
            'fileExt' : '*.xls; *.xlsx',
            'queueID'  : 'excel_file_queue',
            'onUploadSuccess' : function(file, data, response) {
                console.log(file);
                if(data==2){
                  $('#getvalsname1').html(file.name + '上传失败');
                  alert("上传失败");
                }else if(data){
                      var strs=data.split("||");
                      $("#imageArea").append('<div><input type="hidden" name="picture_name['+strs[0]+']" value="'+file.name+'" /></div>');
                      $.post($('#upload').attr('action'),$("#upload").serialize(),function(data){
                           if(data.code==200){
                                alert(data.msg);
                                window.location.reload();       
                           }
                     },'json');
               }
            }
        });


        $('#uploadimg').uploadify({
            'multi'      : true,
            'swf'        : '../upload/uploadify.swf',
            'uploader'   : '../upload/imguploadify.php',
            'buttonText' : '<div align="center">选择商品图片</div>',
            'fileExt'    : '*.jpg; *.png; *.gif; *.jpeg',
            'queueID'    : 'image_file_queue',
            'onUploadSuccess' : function(file, data, response) {
                console.log(file);
                if(data==2){
                  alert("上传失败");
                }else if(data){
                      var strs=data.split("||");
                      $("#goodsimg").append('<div><input type="hidden" name="goodsImg" value="'+file.name+'" /></div>');
                      $("#goodsimg").append('<div><input type="hidden" name="goodsHash" value="'+strs[0]+'" /></div>');
                      $.post('/import/addimage',$("#upload").serialize(),function(result){
                         var s = $('.successNum').text();
                         var f = $('.failNum').text();
                         if(result.success == 1) {
                            $('.successNum').text(parseInt(s) + 1);
                         } else if( result.success == 0 ){
                            $('.failNum').text(parseInt(f) + 1);
                            var str = "<tr><td></td><td>"+result.error+"</td></tr>"
                            $('table').append(str);
                         } else if( result.success == 2 ){
                            alert(result.notice);
                         }
                     },'json');
               }
            }
        });
    });

</script>   