


<div class="wrapper">
    <div id="main" class="container-fluid">
<!-- BreadNav -->
            <div class="row mt10">
                <div class="col-xs-12">
                    <div class="BreadcrumbNav white">
                        <a href="">首页</a>
                        >
                        <a href="">系统管理</a>
                        >
                        <a href="">操作日志</a> 
                    </div>
                </div>
            </div>
        <div class="row mt10">
<!-- search -->            
            <div class="tabhead col-xs-12">
                <div class="setwrap top-search">
                    <button id="setWindow" class="btn btn-primary">列设置</button>
                    <div class="set-window"></div>
                </div>
                <span class='linheit'>总数：<i class='red'><?=$this->total ?></i></span>
            </div>
        </div>
<!-- content-list -->
        <div class="row tablescroll">
            <table id="table" class="scrollTable">
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>用户</td>
                        <td>操作人员</td>
                        <td>操作</td>
                        <td>店铺</td>
                        <td>创建时间</td>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->list as $row): ?>
				  		<tr>
				  			<td><?=$row['id']?></td>
				  			<td><?=$row['uname']?></td>
				  			<td><?=$row['dname']?></td>
				  			<td>
                                <?=$row['aname'].'：'.$row['gname'] . '('.$row['code'].')';if ($row['number']) echo '&nbsp;&nbsp;'.$row['number'].'&nbsp;件'?>
                            </td>
				  			<td><?=$row['sname']?></td>
				  			<td><?=$row['createTime']?></td>
				  		</tr>
			  		<?php endforeach; ?>
                </tbody>
            </table>
        </div>
<!-- page -->
        <div class="row center mb10">
            <div class="pagenav">
                <div id="Pagination" class="flickr">
                    <?=$this->pagebar;?>
                </div>
                <div class="page-count">
                    <div>
                        每页显示<span id="perpage"><?=$this->perpage?></span>条
                        <ul id="pageCountSelect">
                            <li>-- 请选择 --</li>
                            <li>30</li>
                            <li>50</li>
                            <li>100</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
<!-- page-end -->
    </div>
</div>