
<script src="/js/ueditor/ueditor.config.js" ></script>
<script src="/js/ueditor/ueditor.all.min.js"></script>
<script src="/js/test.js/jedate.min.js"></script>


    <div class="wrapper">
        <div id="main" class="container-fluid">
            <div class="row mt10">
                <div class="col-xs-12">
                    <div class="BreadcrumbNav white">
                        <a href="">首页</a>
                        >
                        <a href="">审核管理</a>
                        >
                        <a href="">审核中心</a>
                    </div>
                    
                </div>
                
            </div>
            <div class="row">
                <div class="tabhead col-sm-12">
                    <form action="" method='get'>
                        
                        <div class="btn-group top-search mt10">
                            <span type="button" class="btn btn-primary">批量处理</span>
                            <span id="batch" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="caret"></span>
                            </span>
                            <ul class="batch-menu">
                                <li action="2-1" class="batchChange_2-1">批量审核通过</li>
                                <li action="2-2" class="batchChange_2-2">批量暂过文案</li>
                                <li action="0-0" class="batchChange_0-0">批量驳回申请</li>
                            </ul>
                        </div>
                        
                        <!--<input class="block form-control top-search mt10" type="text" placeholder="提交人" name="uploader" value="<?=$this->uploader?>" />
                         <input name="startTime" id="indate" class="top-search form-control mt10" type="text" placeholder="请输入日期" readonly /><span class="block linheit top-search mt10"> - </span><input name="endTime" id="indate2" class="top-search form-control mt10" type="text"  placeholder="请输入日期" readonly/> -->
                        
                        <div class="btn-group btn-search">
                            <span class="btn btn-default dropdown-toggle mt10">模糊查询<i class="caret"></i></span>
                            <ul class="batch-menu">
                                <li data="1">模糊查询</li>
                                <li data="2">按sku查询</li>
                                <li data="3">按货号查询</li>
                                <li data="4">按提交人查询</li>
                            </ul>
                        </div>
                        <input type="hidden" name="searchType" id="searchType" value="<?=$this->searchType;?>" />
                        <div class="btn-group">
                            <div class="input-group">
                                <input class="block form-control mt10" type="text" placeholder="请输入关键词" name="keyword" value="<?=$this->keyword?>" />
                                <div class="input-group-btn">
                                    <button class="btn btn-default mt10">搜索</button>
                                </div>
                            </div>
                        </div>
                    </form>
                
                    <div class="setwrap top-search mt10">
                        <button id="setWindow" class="btn btn-primary">列设置</button>
                        <div class="set-window"></div>
                    </div>
                    <span class="top-search linheit mt10">数量：<i class="red"><?=$this->total?></i></span>
                </div>
            </div>
            <div class="row tablescroll">
                <table id="table" class="tablewidth scrollTable">
                    <thead>
                        <tr>
                            <td><input id="checkBox" type="checkbox" />全选</td>
                            <td>审核编号</td><td>缩略图</td><td>商品名称</td><td>SKU编码</td><td>进货价</td><td>供应商</td><td>提交人</td><td>提交时间</td><td>操作</td>
                        </tr>
                    </thead>
                    <tbody>
<?php if( !empty($this->list) ): ?>
    <?php foreach( $this->list as $row ): ?>
                        <tr data="<?=$row['id']?>">
                            <td><input type="checkbox" class="batchCheckBox" data="<?=$row['id']?>" name="chkGoods[]" value="<?=$row['id']?>-<?=$row[gid]?>" /></td>
                            <td><?=$row['id']?></td>
                            <td><img src="<?=$row['thumb']?>" onclick="showImg(this)" /></td>
                            <td><?=$row['name']?></td>
                            <td><?=$row['code']?></td>
                            <td><?=$row['purchPrice']?></td>
                            <td><?=$row['shopName']?></td>
                            <td><?=$row['uploaderName']?></td>
                            <td><?=$row['oneTime']?></td>
                            <td>
                                <p><button class="btn btn-yes-0" action="2-1" goodsId="<?=$row['gid']?>" data="<?=$row['id']?>" id="submitBtn_2-1_<?=$row['id']?>">审核通过</button></p>
                                <p><button class="btn btn-yes-1" action="2-2" goodsId="<?=$row['gid']?>" data="<?=$row['id']?>" id="submitBtn_2-2_<?=$row['id']?>">暂无文案</button></p>
                                <p><span class="btn btn-no" action="0-0" goodsId="<?=$row['gid']?>" data="<?=$row['id']?>" id="submitBtn_0_<?=$row['id']?>">驳回申请</span></p>
                            </td>
                        </tr>
                        <tr  data="<?=$row['id']?>">
                            <td colspan="50">
    <form action="/checktwo/singleSave" flag='true' data="<?=$row['id']?>" method="post" >
        <input type="hidden" name="goodsId" value="<?=$row['gid']?>">
        <input type="hidden" name="checkId" value="<?=$row['id']?>">
        <div class="row order-info">
            <div class="col-xs-1">
                    <div class="mt10">商品名称</div>
                    <div class="mt10">进货价格</div>
                    <div class="mt10">商品货号</div>
                    <div class="mt10">图片数量</div>
                    <div class="mt10">淘宝专用名</div>
            </div>

            <div class="col-xs-2">
                <input class="form-control inpwidth100 mt10" type="text" name="name" value="<?=$row['name']?>" readonly/>
                <div class="input-group mt10">
                    <div class="input-group-addon">¥</div>
                    <input type="text" class="form-control inpwidth100" name="purchPrice" value="<?=$row['purchPrice']?>" readonly/>
                    <div class="input-group-addon">.00</div>
                </div>
                <input class="form-control mt10 inpwidth100" type="text" name="goodsNo" value="<?=$row['goodsNo']?>" readonly />
                <div class="input-group mt10">
                    <input type="text" class="form-control inpwidth100" name="" value="<?=$row['imgNum']?>" readonly />
                    <div class="input-group-addon">张</div>
                </div>
                <input class="form-control mt10 inpwidth100" type="text" name="taobaoSpecial" value="<?=$row['taobaoSpecial']?>" readonly />

            </div>
            <div class="col-xs-1 mt10">
                <div>类目</div>
                <div class="mt10">参数</div>
            </div>
            <div class="col-xs-4 mt10">
                <div>
                    <select class="form-control " id="cat_1_<?=$row['id']?>" oldpid="0" oldcat="<?=$row[category1]?>" level="0" data="<?=$row['id']?>" name="category1"disabled="disabled">
                        <option value="">一级类目</option>
                        <?php foreach( $this->cat1 as $cat1 ): ?>
                            <option value="<?=$cat1['id']?>" <?=$row['category1'] == $cat1['id'] ? "selected=selected" : '' ?>><?=$cat1['name']?></option>
                        <?php endforeach;?>
                    </select>
                    <select class="form-control" id="cat_2_<?=$row['id']?>" oldpid="<?$row['category1']?>" oldcat="<?=$row[category2]?>" level="1" data="<?=$row['id']?>" name="category2"disabled="disabled">
                        <option value="">二级类目</option>
                        <?php if( $row['cat2'] ):?>
                            <?php foreach( $row['cat2'] as $cat2 ): ?>
                                <option value="<?=$cat2['id']?>" <?=$row['category2'] == $cat2['id'] ? "selected=selected" : '' ?>><?=$cat2['name']?></option>
                            <?php endforeach;?>
                        <?php endif;?>
                    </select>
                    <select class="form-control" id="cat_3_<?=$row['id']?>" oldpid="<?=$row['category2']?>" level="2" data="<?=$row['id']?>" name="category3" oldcat="<?=$row[category3]?>" goodsId="<?=$row['gid']?>"disabled="disabled">
                        <option value="">三级类目</option>
                        <?php foreach( $row['cat3'] as $cat3 ): ?>
                            <option value="<?=$cat3['id']?>" <?=$row['category3'] == $cat3['id'] ? "selected=selected" : '' ?>><?=$cat3['name']?></option>
                        <?php endforeach;?>
                    </select>
                    <div class="clearfix"></div>
                </div>
                <!-- <div class="text-left mt10">
                    <span id="parameter_<?=$row['id']?>" data="<?=$row['id']?>" class="btn-primary">添加</span>
                </div> -->
            </div>
            <div class="col-xs-4 mt10">
                <div id="key_cat_<?=$row['id']?>">
                <?php if( !empty( $this->attrs[$row['category3']] ) ): ?>
                    <?php foreach( $this->attrs[$row['category3']] as $pid => $value ): ?>
                        <div class="parameter">
                        <p>参数名： <input type="text" name="param[<?=$row['id']?>][<?=$pid?>][key][name]" value="<?=$value['name']?>" readonly /><input type="hidden" name="param[<?=$row['id']?>][<?=$pid?>][key][id]" value="<?=$value['id']?>"></p>
                        <p>参数值：
                            <select name="param[<?=$row['id']?>][<?=$pid?>][value]" disabled="disabled">
                                <option value="0-0">请选择</option>
                                <?php foreach( $value['child'] as $cid => $v ): ?>
                                    <option value="<?=$v[id]?>-<?=$v['name'] ?>" <?=$row['attribute'][$pid]==$v['id'] ? "selected='selected'" : '' ;?>>
                                        <?=$v['name']?>
                                    </option>
                                <?php endforeach;?>
                            </select>
                        </p>
                        <!-- <p><span class="btn-primary" onclick="delParameter(this)">删除</span></p> -->
                        </div>
                    <?php endforeach;?>
                <?php endif;?>
                </div>
                <div id="key_add_<?=$row['id']?>">
                <?php $num=0; ?>
                <?php if( !empty($row['attribute']) ): ?>
                <?php foreach( $row['attribute'] as $k => $v ): ?>
                    <?php if( !is_numeric($k) ): ?>
                        <div class="parameter">
                        <p>参数名： <input type="text" name="param[<?=$row['id']?>]['add_<?=$num;?>'][key]" value="<?=$k?>" readonly/></p>
                        <p>参数值：
                            <input type="text" name="param[<?=$row['id']?>]['add_<?=$num;?>'][value]" value="<?=$v?>" readonly>
                        </p>
                        <!-- <p><span class="btn-primary" onclick="delParameter(this)">删除</span></p> -->
                        </div>
                        <?php $num++;?>
                    <?php endif;?>
                <?php endforeach;?>
                <?php endif;?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-1 mt10">
                <div class="mt10">商品描述</div>
            </div>
            <div class="col-xs-8 mt10 text-left">
                <script id='descript_<?=$row['id']?>' data="<?=$row['id']?>" class='descript' type='text/plain' style="height: 200px;"><?=$row['intro']?></script>
                <div class="editWrap"></div>

                <!-- <div class="editBtn" data="<?=$row['id']?>" gid="<?=$row['gid']?>">
                    <img src="/img/iconfont-bianji.png"/>
                </div> -->
            </div>
        </div>
        <!--< div class="row nomargin mb10">
            <button class="btn btn-primary" data="<?=$row['id']?>" id="singleSave_<?=$row['id']?>">保存修改</button>
            <input class="btn btn-primary" data="<?=$row['id']?>" type="reset" value="恢复初始" id="reset_<?=$row['id']?>"></input> 
        </div>-->
    </form>
                            </td>
                        </tr>
    <?php endforeach;?>
<?php endif;?>
                    </tbody>
                </table>
            </div>
<!-- 点击出现的侧面的富文本编辑器 -->
<!-- <div class="editWrap none">
    <div class="editDiv" >
        <script style="height: 600px; width: 500px;" id="edit" type='text/plain'></script>
        <div class="row">
            <div class="col-xs-12 mt10" id="saveIntro">
                <span gid="" class="record-id"></span>
                <span class="btn btn-primary">确定</span>
                <span class="btn btn-primary">取消</span>
            </div>
        </div>
    </div>
</div> -->
<!-- 富文本编辑器结束 -->
<!-- page -->
        <div class="row center mb10">
            <div class="pagenav">
                <div id="Pagination" class="flickr">
                    <?=$this->pagebar;?>
                </div>
                <div class="page-count">
                    <div>
                        每页显示<span id="perpage"><?=$this->perpage?></span>条
                        <ul id="pageCountSelect">
                            <li>-- 请选择 --</li>
                            <li>10</li>
                            <li>30</li>
                            <li>50</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
<!-- page-end -->  
            
        </div>
    </div>
<!--JavaScript-->
<script>
    //模糊搜索
    // $('#searchType').val(1);
    $('.btn-search').children('.btn').click(function(e){
        e.stopPropagation();
        $(this).next().toggle();
    })
    $('.btn-search').children('.btn').next('.batch-menu').children('li').click(function(){
        $('#searchType').val($(this).attr('data'));
        $('.btn-search').children('.btn').html($(this).text() + '<i class="caret"></i>')
    })
    $(function(){
        $('.descript').each(function(i){
            var $id = $(this).attr('id');
            //var $data = $(this).attr('data');
            var descript = UE.getEditor( $id ,{
                                    toolbars: [
                                       ['source','|', 'undo','|', 'redo'
                                       ,'|','selectall', '|','cleardoc','|', 'removeformat']
                                    ]
                                });

        $('.editWrap').click(function(){
            var id = $(this).prev().attr('id');
            UE.getEditor( id ).setDisabled('fullscreen');
            $(this).hide();
        })
            /*descript.mark = $data;
            descript.addListener('selectionchange',function(){
                $("form[data='"+$(this).attr('mark')+"']").attr('flag',false);
            })*/
        })
    })

    /*var edit = UE.getEditor( 'edit', {
                                toolbars: [
                                   ['source','|', 'undo','|', 'redo'
                                   ,'|','selectall', '|','cleardoc','|', 'removeformat']
                                ]
                            });
window.onload = function(){
    $('.editBtn').click(function(){
        var $edit = $('.editWrap');
        if($edit.hasClass('none')){
            $edit.removeClass('none').css('right','-500px');
            $edit.animate({'right':0},300);
        }
        var gid = $(this).attr('gid');
        $('.record-id').attr('gid',gid);
        $.post('/checktwo/getIntro',{'gid':gid},function(result){
            console.log(result);
            var content = result.data;
            UE.getEditor('edit').setContent( content );
        },'json');
    })
    $('#saveIntro').bind({
        click:function(e){
            var $target = $(e.target);
            if( $target.text() == '确定' ){
                var gid = $('.record-id').attr('gid');
                var intro = UE.getEditor('edit').getContent();
                $.post('/checktwo/saveIntro',{'gid':gid,'intro':intro},function(result){
                    if( result.success == 1 ){
                        alert(result.data);
                    }else{
                        alert(result.error);
                    }
                },'json');
            }else if( $target.text() == '取消' ){
                $('.editWrap').animate({'right':'-500px'},300,function(){
                    $(this).addClass('none').css('right','-100%');
                });
            }
        }
    });
}
    $('.editWrap').click(function(){
        $(this).animate({'right':'-500px'},300,function(){
            $(this).addClass('none').css('right','-100%');
        });
    })
    $('.editWrap').children('.editDiv').click(function(e){
        e.stopPropagation();
    })*/

    //添加商品属性参数
    $("[id^='parameter_']").each(function(i){
        var index = i;
        $(this).click(function(){
            var id = $(this).attr('data');
            var $last = $(this).parent().next();
            if( $last.length == 0 ){
                var num = 0 ;
            }else{
                var num = parseInt($last.attr('num')) + 1;
            }
            $(this).parent().after($('<div class="parameter" num="'+num+'"><p>参数名<input type="text" name="param['+id+'][add_new_'+num+'][key]" value="" /></p><p>参数值<input type="text" name="param['+id+'][add_new_'+num+'][value]" value=""/></p><p><span class="btn-primary" onclick="delParameter(this)">删除</span></p></div>'));
            $(this).parent().parent().parent().parent().attr('flag','false');
        })
    })
    
    function delParameter(obj){
        $(obj).parent().parent().remove();
    }
    
    $("[id^='cat_']").bind({
        change:function(){
            var id = $(this).attr('data');
            var oldpid = $(this).attr('oldpid');
            var oldcat = $(this).attr('oldcat');
            var level = $(this).attr('level');
            var pid = $(this).find('option:selected').val();
            if( !pid ) return;
            var relation = ['category','category','getCurrentAllAttrs'];
            var send = {'pid':pid};
            if( level == 2 && oldcat == pid ){
                var gid = $(this).attr('goodsId');
                send = {'pid':pid,'type':'now','gid':gid};
            }
            var _this = $(this);//console.log(send);return;
            $.post('/checktwo/'+relation[level],send,function(result){
                if(result.success == 1){
                    var data = result.data;
                    var len = data.length;
                    var str='';
                    if( level != 2 ){
                        for( var i=0;i<len;i++ ){
                            str += "<option value="+data[i].id+">"+data[i].name+"</option>";
                        }
                        _this.next().find('option:gt(0)').remove();
                        if( level == 0 ){
                            _this.next().next().find('option:gt(0)').remove();
                        }
                        _this.next().append(str);
                    }else{
                        //console.log(result.data);return;
                        if( result.data ){
                            attr = data[pid];
                            len = attr.length;
                            var attribute = null;
                            if( oldcat == pid  ) attribute = data['now'];
                            var id1,id2;
                            for( id1 in attr ){
                                str += "<div class='parameter'><p>参数名： <input type='text' value='"+attr[id1].name+"' name='param["+id+"]["+id1+"][key][name]' /></p><input type='hidden' name='param["+id+"]["+id1+"][key][id]' value='"+id1+"' /> <p>参数值： <select name='param["+id+"]["+id1+"][value]' id='' ><option value='0-0'>请选择</option>";
                                var child = attr[id1].child;
                                for( id2 in child ){
                                    str += "<option value='"+id2+"-"+child[id2].name+"' ";
                                    if( attribute ){
                                        if( attribute[id1] == id2 ){
                                            str += "selected='selected'";
                                        }
                                    }
                                    str += " >"+child[id2].name+"</option>" ;
                                }
                                str += "</select></p> <p><span class='btn-primary' onclick='delParameter(this)'>删除</span></p></div>";
                            }
                            $("[id^='key_cat_"+id+"']").html('');
                            $("[id^='key_cat_"+id+"']").html(str);
                        }
                    }
                }else if( result.success == 0 ){
                    alter(result.error);
                }else if( result.success == 2 ){
                    alert(result.notice);
                }
            },'json');
        }
    });

   /* $("[id^='reset_']").bind({
        click:function(){
            var id = $(this).attr('data');
            $("[id='cat_3_"+id+"']").tirgger('change');
        }
    });*/

    $("[id^=singleSave_").bind({
        click:function(){
            var id = $(this).attr('data');
            $.post('/checktwo/singleSave',$("form[data='"+id+"']").serialize(),function(result){
                if( result.success == 1 ){
                    $("form[data='"+id+"']").attr('flag','true');
                    alert(result.data);
                }else if( result.success == 0 ){
                    alert(result.error);
                }else if( result.success == 2 ){
                    alert(result.notice);
                }
            },'json');
            return false;
        }
    });

    $("[id^='submitBtn_']").bind({
        click:function(){
            var id = $(this).attr('data');
            var gid = $(this).attr('goodsId');
            var action = $(this).attr('action');
            var currentFormFlag = $("form[data='"+id+"']").attr('flag');
            if( currentFormFlag == 'false' ){
                alert('本条记录没有保存！\n请点击保存后再试！');
                return;
            }else{//console.log(action);return;
                $.post('/checktwo/change',{'id':id,'gid':gid,'action':action},function(result){
                    if( result.success == 1 ){
                        $("tr[data='"+id+"']").remove();
                        alert(result.data);
                    }else if( result.success == 0 ){
                        alert(result.error);
                    }else if( result.success == 2 ){
                        alert(result.notice);
                    }
                },'json');
            }
        }
    });

    $('#batch').click(function(e){
        e.stopPropagation();
        $(this).next().toggle();
    });

    $("[class^='batchChange_']").bind({
        click:function(){
            var action = $(this).attr('action');
            var checked = $('.batchCheckBox:checked');
            var chked = false;
            var flag = new Array();
            for( var i=0,len=checked.length;i<len;i++ ){
                if( checked[i].checked ){
                    chked = true;
                    var id = $(checked[i]).attr('data');
                    if( $("form[data='"+id+"']").attr('flag') == 'false' ){
                        flag.push(id);
                    }
                }
            }
            if( !chked ){
                alert('请至少选择一件商品！');
                return false;
            }
            if( flag.length > 0 ){
                var msg = flag.join(',');
                alert('ID为:( '+msg+' )的商品没有保存!');
                return false;
            }

            var send = $('.batchCheckBox:checked').serialize();
            $.post('/checktwo/batchChange?action='+action,send,function(result){
                if( result.success == 1 ){
                    alert(result.data);
                    window.location.href='/checktwo/index';
                }else if( result.success == 0 ){
                    alert(result.error);
                }else if( result.success == 2 ){
                    alert(result.notice);
                }
            },'json');
        }
    });

    var sw = false;
    $('#checkBox').bind({
        click:function(){
            $('.batchCheckBox').prop({"checked":!sw});
            sw = !sw;
        }
    });

    /*//日期
    jeDate({
        dateCell:"#indate",//isinitVal:true,
        format:"YYYY-MM-DD",
        isTime:false, //isClear:false,
        minDate:"2015-10-19 00:00:00",
        maxDate:"2016-11-8 00:00:00"
    })
    jeDate({
        dateCell:"#indate2",//isinitVal:true,
        format:"YYYY-MM-DD",
        isTime:false, //isClear:false,
        minDate:"2015-10-19 00:00:00",
        maxDate:"2016-11-8 00:00:00"
    })*/

    function formChange(){
        var $form = $('#table').find('form');
        var form = document.getElementById("table").getElementsByTagName('form');
        
        for(var i=0;i<$form.length;i++){
            //input
            var inp = form[i].getElementsByTagName('input');
            for(var j=0;j<inp.length;j++){
                inp[j].setAttribute("index",i);
            }
            $form.eq(i).find('input').bind('input',function(){
                //alert($(this).attr('index'));
                $form.eq($(this).attr('index')).attr('flag','false');
            })

            var slt = form[i].getElementsByTagName('select');
            for(var k=0;k<slt.length;k++){
                slt[k].setAttribute("index",i);
            }
            $form.eq(i).find('select').bind('change',function(){
                //alert('下拉改变');
                $form.eq($(this).attr('index')).attr('flag','false');
            })
        }
    }

    formChange();
</script>