<script type="text/javascript" charset="utf-8" src="/js/ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="/js/ueditor/ueditor.all.min.js"> </script>
<div class="wrapper">
    <div id="main" class="scrollbar container-fluid">
      <div class="row mt10">
        <div class="col-xs-12">
          <div class="BreadcrumbNav white">
            <a href="">首页</a>
            >
            <a href="">版本管理</a>
            >
            <a href="">添加版本</a>
          </div>
        </div>
      </div>
      <div class="row mt10">
        <div class="col-lg-2">
          <div class="leftinfo">
            <ul>
              <li class="active"><div>基础信息</div></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-9 neworder-info">
          <h4 class="tit">版本信息</h4>
          <hr />
<form method="POST"  id="form" enctype="multipart/form-data">

    <div class="row childpad">
        <label class="col-lg-1 col-md-2 control-label">版本号</label>
        <div class="col-sm-4">
            <input type="text" name="code" class="form-control" value="<?=$this->Info['code']?>" >
        </div>
    </div>
<!--    <div class="row childpad">
        <label class="col-lg-1 col-md-2 control-label">创建时间</label>
        <div class="col-sm-4">
            <input type="text" name="updateTime" class="form-control" value="<?=$this->Info['createTime']?>" readonly/>
        </div>
    </div>
-->
    <div class="row childpad">
        <label class="col-md-2 col-lg-1 control-label">版本描述</label>
        <div class="col-md-10 col-lg-9">
            <script id="textarea" name="descript" type="text/plain" style="height: 220px;"><?=htmlspecialchars_decode($this->Info['descript'])?></script>
        </div>
    </div>
    <div class="row childpad mt10">
        <label class="col-md-2 col-lg-1 control-label">版本文件</label>
        <div class="col-md-10 col-lg-9">
            <a class="btn btn-primary"><img alt="文件" ></a>
            <input type="file" name="file" class="form-control" style="width: 100%;height:100%;"/>
        </div>
    </div>
	
    <div class="row childpad mt10">
        <label class="col-md-2 col-lg-1 control-label">强制更新</label>
        <div class="col-md-10 col-lg-9">
            <input type="radio" name="is_must" class="form-control" value="0"/>否
            <input type="radio" name="is_must" class="form-control" value="1"/>是
        </div>
    </div>
	<div class="form-group">
        <button type="button" class="btn btn-primary" id="submitBtn">保存添加</button>
    </div>
        
	<script>
        $(function(){
       	 //实例化编辑器
            //建议使用工厂方法getEditor创建和引用编辑器实例，如果在某个闭包下引用该编辑器，直接调用UE.getEditor('editor')就能拿到相关的实例
            //var ue = UE.getEditor('textarea');
            var ue = UE.getEditor('textarea',{
                    toolbars: [
                               ['fullscreen', 'source', 'undo', 'redo'],
                               ['selectall', 'cleardoc', 'removeformat']
                            ]
                    });
            $('#submitBtn').click(function() {
                var $editor = $("[name='descript']").val();
                var $file = $("[name='file']").val();
                if ( $.trim($editor) == '' ) {
                    alert('请填写版本描述');
                    return false;
                }
                if ( $.trim($file) == '' ) {
                    alert('请上传版本文件');
                    return false;
                }
                $('#form').submit();
            })
        })
	</script>
</form>
        </div>
    </div>
</div>
