<script type="text/javascript" charset="utf-8" src="/js/ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="/js/ueditor/ueditor.all.min.js"></script>
<script type="text/javascript" charset="utf-8" src="/js/jquery.sortable.js"> </script>
<script type="text/javascript" charset="utf-8" src="/js/lightbox.js"> </script>
<div class="wrapper">
        <div id="main" class="scrollbar container-fluid">
            <div class="row mt10">
                <div class="col-xs-12">
                    <div class="BreadcrumbNav white">
                        <a href="">首页</a>
                        >
                        <a href="">推送商品管理</a>
                        >
                        <a href="">新建订单</a>
                    </div>
                    
                </div>
                
            </div>
            <form method="post"  enctype="multipart/form-data">
            <input type="hidden" name="id" value="<?=$this->Info['id']?>">
            <div class="row mt10">
                <div class="col-lg-2">
                    <div class="leftinfo">
                        <ul>
                            <li class="active"><div>版本管理</div></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-9 neworder-info">
                    <h4 class="tit">版本信息</h4>
                    <hr />
                    
                    <div class="row childpad">
                        <label class="col-lg-1 col-md-2 control-label">版本号</label>
                        <div class="col-sm-4">
                            <input type="text" name="code" class="form-control" value="<?=$this->Info['code']?>" >
                        </div>
                    </div>
                    <div class="row childpad">
                        <label class="col-lg-1 col-md-2 control-label">创建时间</label>
                        <div class="col-sm-4">
                            <input type="text" name="updateTime" class="form-control" value="<?=$this->Info['createTime']?>" readonly/>
                        </div>
                    </div>
                    <div class="row childpad">
                        <label class="col-md-2 col-lg-1 control-label">版本描述</label>
                        <div class="col-md-10 col-lg-9">
                            <script id="textarea" name="descript" type="text/plain" style="height: 220px;"><?=htmlspecialchars_decode($this->Info['descript'])?></script>
                        </div>
                    </div>
                    <div class="row childpad mt10">
                        <label class="col-md-2 col-lg-1 control-label">版本文件</label>
                        <div class="col-md-10 col-lg-9">
                            <a class="btn btn-primary"><img alt="文件" ></a>
                            <input type="file" name="file" class="form-control" style="width: 100%;height:100%;"/>
                        </div>
                    </div>
                    
                    <div class="row childpad mt10">
                        <label class="col-md-2 col-lg-1 control-label">强制更新</label>
                        <div class="col-md-10 col-lg-9">
                            <input type="radio" name="is_must" class="form-control" value="0" <?php if(!$this->Info['is_must']) echo "checked";?>/>否
                            <input type="radio" name="is_must" class="form-control" value="1" <?php if($this->Info['is_must']) echo "checked";?>/>是
                        </div>
                    </div>
                    
                </div>
            </div>
            
            <div class="row mt10 mb50 neworder-btn">
                <div class="col-lg-2"></div>
                <div class="col-lg-9">
                    <button class="btn btn-primary">保存修改</button>
                </div>
                
            </div>
            </form>
        </div>
    </div>
<script>
    //var ue = UE.getEditor('textarea');
    var ue = UE.getEditor('textarea',{
            toolbars: [
                       ['fullscreen', 'source', 'undo', 'redo'],
                       ['selectall', 'cleardoc', 'removeformat']
                    ]
            });
</script>