
	<div class="wrapper">
		<div id="main" class="scrollbar container-fluid">
			<div class="row mt10">
				<div class="col-xs-12">
					<div class="BreadcrumbNav white">
						<a href="">首页</a>
						>
						<a href="">详情模板管理</a>
						>
						<a href="">添加模板</a>
					</div>
					
				</div>
				
			</div>
			<form method="post" action="/goodstemplet/save" id="form" enctype="multipart/form-data">
            <div class="row mt10">
            	<div class="col-lg-2">
					<div class="leftinfo">
						<ul>
							<li class="active"><div>模板信息</div></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-9 neworder-info">
					<div class="row childpad">
					<h4 class="tit">选择类目</h4>
						<hr />

	        <!--<label class="col-lg-1 col-md-2 control-label text-right">选择类目</label>-->
				        <div class="col-sm-3 classifywrap mb10" level="0">
				            <div class="classifymenu" level="0">
				                <div class="classifysearch">
				                    <input type="text" />
				                    <span><img src="/img/classifysearch.png"/></span>
				                </div>
				                <ul class="classifylist" level="0">
				                    <?php foreach ($this->category1 as $v): ?>
				                        <li value="<?=$v['id'] ?>" class="<?= $v['id']==$this->Info['category1'] ? 'active':'';?>" onclick="category(this)"><?=$v['name'] ?></li>
				                    <?php endforeach; ?>
				                </ul>
				                <input type="hidden" name="category1" value="<?=$this->Info['category1']?>">
				            </div>
				        </div>
				        <div class="col-sm-3 classifywrap mb10" level="1">
				            <div class="classifymenu <?=empty($this->category2)?'none':'';?>" level="1">
				                <div class="classifysearch">
				                    <input type="text" />
				                    <span><img src="/img/classifysearch.png"/></span>
				                </div>
				                <ul class="classifylist" level="1" >
				                    <?php foreach ($this->category2 as $v): ?>
				                        <li value="<?=$v['id'] ?>" class="<?=$v['id']==$this->Info['category2']?'active':''?>" onclick="category(this)"><?=$v['name'] ?></li>
				                    <?php endforeach; ?>
				                </ul>
				                <input type="hidden" name="category2" value="<?=$this->Info['category2']?>">
				            </div>
				        </div>
				        <div class="col-sm-3 classifywrap mb10" level="2">
				            <div class="classifymenu <?=empty($this->category3)?'none':'';?>" level="2">
				                <div class="classifysearch">
				                    <input type="text" />
				                    <span><img src="/img/classifysearch.png"/></span>
				                </div>
				                <ul class="classifylist" level="2">
				                    <?php foreach ($this->category3 as $v): ?>
				                        <li value="<?=$v['id'] ?>" class="<?=$v['id']==$this->Info['category3']?'active':''?>" onclick="category(this)"><?=$v['name'] ?></li>
				                    <?php endforeach; ?>
				                </ul>
				                <input type="hidden" name="category3" value="<?=$this->Info['category3']?>">
				            </div>
				        </div>
			        <!-- <div class="col-sm-2 mb10">
			            <span class="btn btn-primary">添加商品目录</span>
			        </div> -->
			    	</div>
				</div>
	        

			</div>
			<div class="row mt10">
            	
				<ul id="modul" class="col-lg-9 col-lg-offset-2">
					<li class="neworder-info modul">
						<h4 class="tit">模块信息</h4>
						<hr />
						<div class="row childpad">
						    <div class="col-lg-2 col-md-3 mb10">
							    <div class="checkbox-group">
								    <input type="checkbox">
								    <span>主标题</span>
								</div>
							</div>
							<div class="col-sm-6 mb10">
						      	<input type="text" class="form-control" name="main_title[]"/>
						    </div>
						</div>
						<div class="row childpad">
						    <div class="col-lg-2 col-md-3 mb10">
							    <div class="checkbox-group">
								    <input type="checkbox">
								    <span>副标题</span>
								</div>
							</div>
							<div class="col-sm-6 mb10">
						      	<input type="text" class="form-control" name="small_title[]" />
						    </div>
						</div>
						<div class="row childpad">
						    <div class="col-lg-2 col-md-3 mb10">
							    <div class="checkbox-group">
								    <input type="checkbox" onclick="changeState(this)">
								    <input type="hidden" name="is_img[]" value="0">
								    <span>引入图片</span>
								</div>
							</div>
						</div>
						<div class="row childpad">
						    <div class="col-lg-2 col-md-3 mb10">
							    <div class="checkbox-group">
							    	<input type="checkbox" onclick="changeState(this)">
								    <input type="hidden" name="is_spec[]" value="0">
								    <span>引入规格</span>
								</div>
							</div>
						</div>

						<div class="row childpad">
						    <div class="col-lg-2 col-md-3 mb10">
							    <div class="checkbox-group">
								    <input type="checkbox">
								    <span>添加描述</span>
								</div>
							</div>
							<div class="col-sm-6 mb10">
						      	<textarea name="info[]"></textarea>
						    </div>
						</div>
						
						
						<div class="row childpad">
						    <div class="col-lg-2 col-md-3 mb10">
							    <div class="checkbox-group">
								    <input type="checkbox">
								    <span>添加图片</span>
								</div>
							</div>
						    <div class="col-md-10 col-lg-10">
						    	<ul class="row detailsimg details-group">
									<li><img class="img-thumbnail" src="/img/newimg.gif"/><input class="fileInput" onchange="addImg(this)" type="file" name="file[]" num="0" multiple="multiple" /></li>
								</ul>
								<ul class="dragUl row detailsimg details-group"></ul>
						    </div>
						</div>
						
						<div class="row childpad text-right modul-info">
							<span onclick="deleteThisModul(this)" class="btn btn-default">删除</span>
						</div>
						<div>
							<input type="hidden" class="sort" name="sort[]" value="1">
						</div>
					</li>
					
					
				</ul>
				
			</div>
			<input type="hidden" id="cat_id" name="cat_id" value="">
			<input type="hidden" id="cat_name" name="cat_name" value="">
            </form>
			
			<div class="row mt10">
				<div class="col-lg-2"></div>
				<div class="col-lg-9">
					<div class="row childpad text-right modul-info">
						<span class="btn btn-yes-1" onclick="cloneLi()">新增</span>
						<span class="btn btn-no">保存</span>
						<span class="btn btn-default " onclick="goback()">返回</span>
					</div>
				</div>
			</div>
		</div>
	</div>
<!--JavaScript-->
<script type="text/javascript" src="/js/test.js/jquery.dragsort-0.5.2.js" ></script>
<script type="text/javascript">
	function category(obj){
        var parent = $(obj).parent();
        var pid = $(obj).val();
        $(obj).addClass('active').siblings().removeClass('active');
        var level = parseInt(parent.attr('level'));
        var relation = new Array();
        relation = ['category','category','getPara'];
        parent.next().attr('value',pid);
        $.post('/checkone/'+relation[level],{'pid':pid},function(result){
            if( result.success == 1 ){
                var str='';
                if( level == 0 ){
                    $(".classifylist:gt("+level+")").html('');
                    $(".classifymenu:gt("+level+")").hide();
                    var data = result.data;
                    var len = data.length;
                    for( var i=0;i<len;i++ ){
                        str += '<li value="'+data[i].id+'" onclick="category(this)">'+data[i].name+'</li>';
                    }
                    var next = level + 1;
                    $(".classifylist[level='"+next+"']").html(str);
                    $(".classifymenu[level='"+next+"']").show();
                }
                if( level == 1 ){
                	$(".classifylist:gt("+level+")").html('');
                    $(".classifymenu:gt("+level+")").hide();
                    var data = result.data;
                    var len = data.length;
                    for( var i=0;i<len;i++ ){
                        str += '<li value="'+data[i].id+'" class="cat3">'+data[i].name+'</li>';
                    }
                    var next = level + 1;
                    $(".classifylist[level='"+next+"']").html(str);
                    $(".classifymenu[level='"+next+"']").show();
                }              
            }
        },'json')
    }

    $('.classifywrap').find('input').keyup(function(){
            var txt = $(this).val();
            $(this).parent().siblings().children('li').hide();
            $.each($(this).parent().siblings().children('li'),function(){
                if($(this).text().indexOf(txt) >= 0){
                    $(this).show();
                }
            })
    });

    $(document).on("click", '.cat3',function() {
    	var thirdId = $(this).val();
    	var thirdName = $(this).text();
    	$(this).addClass('active').siblings().removeClass('active');
    	$('#cat_id').val(thirdId);
    	$('#cat_name').val(thirdName);
        $.post('/goodstemplet/checkIsHasTemplet',{'cat_id':thirdId},function(result) {
        	var html = '';
        	html += result;
            $('#modul').html(html);          
            li = $('#modul').children('li');
      		li.find('.dragUl').dragsort();
			modulCheckGroup(li);
        },'text')

    })


	$('#modul input,textarea').click(function(evt){
		if(!$('#checkSelect').val()){
			$_confirm('请先选择类目',function(){

			})
		}
	})
	
	$('.btn-no').click(function(){		
		var cat_id = $('.cat3').val();
		if(cat_id){
			var $info = $('#main').find('li.neworder-info');
			for(var i=0;i<$info.length;i++){
				var _this = $info.eq(i);
				_this.find('.sort').val(i+1);
				var $input = _this.find('.dragUl li input');
				for(var j=0;j<$input.length;j++){
					var name = $input.eq(j).attr('name');
					name = name.replace(/imgSort\[\d*\]/,'imgSort['+(i)+']');
					$input.eq(j).attr('name',name);
					$input.eq(j).val(j);					
				}	
			}
			$('#form').submit();
		}else{
			$_confirm('请先选择类目',function(){

			});
		}    
	})
	function changeState(v){
		if ($(v).next().val()=='1') {
			$(v).next().val('0');
		}else{
			$(v).next().val('1');
		}
	}

	function goback(){
		location.href='/goodstemplet/index';
	}
</script>
<script>	
	//新增模块
	var $modul = $('#modul').children('li').clone();
	function cloneLi(){
		var $nextModul = $modul.clone();
		$('#modul').append($nextModul);
		$nextModul.find('.dragUl').dragsort();
		modulCheckGroup($nextModul);
	}
	//复选框	
	modulCheckGroup($('#modul').children('li'));
	function modulCheckGroup(obj){
		obj.find('.checkbox-group').click(function(){
	        if($(this).children('input').is(':checked')){
	            $(this).children('input').prop('checked',false);
	            $(this).children('input:hidden').val('0');
	        }else {
	            $(this).children('input').prop('checked',true);
	            $(this).children('input:hidden').val('1');
	        }
	    })
	    obj.find('.checkbox-group').children('input').click(function(e){
	        e.stopPropagation();
	    })
	}
		
	//删除本模块
	function deleteThisModul(obj){
		var $li = $(obj).parent().parent();
		if($('#modul').children('li').length>1){
			$_confirm('确定要删除该模块吗？',function(){
				$li.remove();
			})
		}else {
			$_confirm('至少要留一个');		
		}
		
	}

//上传图片
	function addImg(obj){
		var num = parseInt($(obj).attr('num'));
		var showBox = obj.parentNode.parentNode.parentNode.getElementsByClassName('dragUl')[0];
		var file = obj;
		var fileList = file.files;
		for(var i=0;i<fileList.length;i++){
			var reader = new FileReader();
			reader.readAsDataURL(fileList[i]);
			reader.index = i;
			reader.num = num;
			reader.onload = function(){
				showBox.innerHTML+='<li><img class="img-thumbnail" src="'+this.result+'"/><div num="'+this.num+'" class="imgdel" index="'+this.index+'"><span class="fr btn btn-primary newimage">删除</span><span class="fl btn btn-primary" onclick="showImg(JSsiblings(this.parentNode))">查看原图</span><input type="hidden" class="imgSort" name="imgSort[][up'+this.num+']['+this.index+']" value="'+num+'" /></div></li>';
			}
		}
		var li = $(obj.parentNode.parentNode.parentNode.parentNode.parentNode).index();
		$(obj).attr('name','file['+li+'][up'+num+'][]').hide();
		var $inp = $('<input onchange="addImg(this)" class="fileInput" type="file" name="file[]" num="'+(num+1)+'" multiple="multiple" />');
		$(obj).parent().append($inp);
	}

//删除新上传的图片
	$('#modul').on('click','.imgdel .newimage',function(){
		if( confirm('你确定要删除吗？') ){
            //获取删除图片的批次和索引
            var num = $(this).parent().attr('num'),index = $(this).parent().attr('index');
            //记录删除file标签的具体某个索引图片
            $(this).parent().parent().parent().append('<input type="hidden" name="delImg[][up'+num+']['+index+']" value="'+num+'-'+index+'"/>')
            //删除页面内的显示图片
            $(this).parent().parent().remove();
        }
	})

//图片排序
	$(".dragUl").dragsort();
	$('#modul').dragsort({dragSelectorExclude:'span, input, textarea'});
	

</script>

