
<div id="navright" class="col-md-4 col-md-offset-2">
  <div class="indexsearch">
    <ul>
      <li><!--<span>1</span>--></li>
      <li>
        <p><?=$this->_developer['name']?></p>
        <div class="usercenter">
          <a href="/developer/edit" style="color:black"><span>个人资料</span></a>
          <span id="pwdBtn">修改密码</span>
          <a href="/developer/signout" style="color:black"><span>退出登录</span></a>
        </div>
      </li>
      <div class="clearfix"></div>
    </ul>
  </div>
</div>