<!--修改密码窗口-->
	<div id="changePwd">
		<div class="change-pwd">
			<div class="container-fluid">
			<form action="/developer/updatepwd" id="formPwd" method="POST">
				<div class="row mt10">
					<div class="col-xs-4 col-xs-offset-4 text-center"><img src="/img/pwd.png"/></div>
					<div id="pwdClose" class="col-xs-2 col-xs-offset-2 text-right pwd-close">x</div>
				</div>
				<div class="row">
					<div class="col-xs-12 text-center pwd-close">修改登录密码</div>
				</div>
				<div class="row">
					<div class="col-xs-12 text-center pwd-tips">请输入8-20位字符，必须用数字，字母，符号两种组合，如果不修改密码请勿填写</div>
				</div>
				<input type="text"  style="display:none" disableautocomplete autocomplete="off">
				<input type="password"  style="display:none" disableautocomplete autocomplete="off">
				<div class="row info-col">
					<div class="col-xs-4 col-sm-3 text-right">旧密码</div>
					<div class="col-xs-8 col-sm-9"><input class="form-control" type="password" name="current" placeholder="旧密码" required autofocus/></div>
				</div>
				<div class="row info-col">
					<div class="col-xs-4 col-sm-3 text-right">新密码</div>
					<div class="col-xs-8 col-sm-9"><input class="form-control" type="password"  name="password" placeholder="新密码" required autofocus/></div>
				</div>
				<div class="row info-col">
					<div class="col-xs-4 col-sm-3 text-right">确认新密码</div>
					<div class="col-xs-8 col-sm-9"><input class="form-control" type="password"  name="confirm" placeholder="请再输入一次" required autofocus/></div>
				</div>
				<div class="row info-col">
					<div class="col-xs-12 text-right">
						<button type="button" id="submitPwd" class="btn btn-primary">确认</button>
						<span id="pwdCancel" class="btn btn-cancel">取消</span>
					</div>
				</div>
				</form>
			</div>
		</div>
	</div>
	<!--修改密码窗口结束-->
<script>
	//提交表单
	$('#submitPwd').click(function() {
	    $('#formPwd').submit();
	})
	//修改密码
	$('#pwdBtn').click(function(){
		$('#changePwd').show();
		$('#pwdClose').css('cursor','pointer');
	})
	
	$('#pwdClose').click(function(){
		$('#changePwd').hide();
	})
	$('#pwdCancel').click(function(){
		$('#changePwd').hide();
	})
</script>