


<div class="wrapper">
    <div id="main" class="container-fluid">
<!-- BreadNav -->
            <div class="row mt10">
                <div class="col-xs-12">
                    <div class="BreadcrumbNav white">
                        <a href="">首页</a>
                        >
                        <a href="">审核管理</a>
                        >
                        <a href="">推送审核</a>
                    </div>
                    
                </div>
                
            </div>
        <div class="row mt10">
<!-- search -->            
            <div class="tabhead col-xs-12">
                <form action="" method='get'>
                        <span class="top-search linheit">分销商：</span>
                        <select class="form-control top-search" name="channel">
                            <?php if( $this->dis ): ?>
                                <option value="">全部</option>
                                <?php foreach( $this->dis as $v ):?>
                                    <option value="<?=$v['id']?>" <?php if($this->channel==$v['id']) echo "selected='selected'"; ?>><?=$v['name']?></option>
                                <?php endforeach;?>
                            <?php endif;?>
                        </select>
                        
                        
                        <div class="btn-group btn-search">
                            <span class="btn btn-default dropdown-toggle">模糊查询<i class="caret"></i></span>
                            <ul class="batch-menu">
                                <li data="1">模糊查询</li>
                                <li data="2">按sku查询</li>
                                <li data="3">按货号查询</li>
                            </ul>
                        </div>
                        <input type="hidden" name="searchType" id="searchType" value="<?=$this->searchType;?>" />
                        <input type="hidden" name="showType" value="<?=$this->showType;?>" />
                        <div class="btn-group">
                            <div class="input-group">
                                <input name="keyword" value="<?=$this->keyword?>" class="form-control" type="text" placeholder="请输入关键词" />
                                <div class="input-group-btn">
                                    <button class="btn btn-default">搜索</button>
                                </div>
                            </div>
                        </div>           
                    
                </form>
<!-- export -->
            
                    <div class="setwrap top-search">
                        <button id="setWindow" class="btn btn-primary">列设置</button>
                        <div class="set-window"></div>
                    </div>
                    <a class="btn btn-primary top-search" href='/push/export'>导出所有商品</a>
                    <span class='linheit'>总数：<i class='red'><?=$this->total ?></i></span>
            </div>
            <div class="row mt10 finance-ul">
                <div class="col-xs-12">
                    <ul>
                        <li class="finance-btn <?php if ($this->showType == 'pingtai') echo ' active '; ?> "><a href="?showType=pingtai&keyword=<?=$this->keyword;?>&serchType=<?=$this->serchType?>&channel=<?=$this->channel;?>"><p>平台商品<span><?=$this->pingtaiTotal?></span></p></a></li>
                        <li class="finance-btn <?php if ($this->showType == 'shangjia') echo ' active '; ?> "><a href="?showType=shangjia&keyword=<?=$this->keyword;?>&serchType=<?=$this->serchType;?>&channel=<?=$this->channel;?>"><p>商家商品<span><?=$this->shangjiaTotal?></span></p></a></li>
                        <div class="clearfix"></div>
                    </ul> 
                </div>                
            </div>
        </div>
<!-- content-list -->
        <div class="row tablescroll">
            <table id="table" class="scrollTable">
                <thead>
                    <tr>
                        <td><input id="checkBox" type="checkbox" />全选</td>
                        <td class="none">ID</td><td>推送来源</td><td>缩略图</td><td>商品名称</td><td>商品参数</td><td>SKU编码</td><td class="none">货号</td><td>渠道价</td><td class="none">市场参考价</td><td>分销渠道</td><td>操作</td>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->list as $row): ?>
                    <tr>
                        <td><input type="checkbox" /></td>
                        <td class="none"><?=$row['id']?></td>
                        <td>
                            <?php if( $row['fromWhere'] == 1 ):?>
                                商家商品
                            <?php else:?>
                                平台商品
                            <?php endif;?>
                        </td>
                        <td><img onclick='showImg(this)' src="<?=$row['thumb']?>" /></td>
                        <td><?=$row['name']?></td>
                        <td>
                            <?php if ( json_decode($row['attribute'],true) ): ?>
                            <?php foreach(json_decode($row['attribute'],true) as $v): ?>
                                <?php if($v['value']['name']!='0'):?>
                                    <p>
                                        <?=$v['key']['name']?>:
                                        <span><?=$v['value']['name']?></span>
                                    </p>
                                <?php endif;?>
                            <?php endforeach;?>
                            <?php endif; ?>
                        </td>
                        <td><?=$row['code']?></td>
                        <td class="none"><?=$row['goodsNo']?></td>
                        <td><?php if ($row['ctimes'] && $row['ptimes']) echo ($row['purchPrice'] *$row['ptimes']* $row['ctimes']  );else echo ''?></td>
                        <td class="none"><?php if ($row['mtimes']) echo ($row['purchPrice'] * $row['mtimes']);else echo ''?></td>
                        <td><?= $row['cname'] ? $row['cname'] : 无 ?></td>
                        <td width="60px">
                            <p><a href="/checkpush/edit/?id=<?=$row['id']?>&page=<?=$this->page;?>&keyword=<?=$this->keyword;?>&channel=<?=$this->channel;?>"><span class="btn-orderDetails btn btn-default"><img src="/img/bianji.png"><i>编辑</i></span></a></p>
                        </td>
                    </tr>
                <?php endforeach;?>
                </tbody>
            </table>
        </div>
<!-- page -->
        <div class="row center mb10">
            <div class="pagenav">
                <div id="Pagination" class="flickr">
                    <?=$this->pagebar;?>
                </div>
                <div class="page-count">
                    <div>
                        每页显示<span id="perpage"><?=$this->perpage?></span>条
                        <ul id="pageCountSelect">
                            <li>-- 请选择 --</li>
                            <li>30</li>
                            <li>50</li>
                            <li>100</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
<!-- page-end -->
    </div>
</div>

<script type="text/javascript">
    //模糊搜索
    // $('#searchType').val(1);
    $('.btn-search').children('.btn').click(function(e){
        e.stopPropagation();
        $(this).next().toggle();
    })
    $('.btn-search').children('.btn').next('.batch-menu').children('li').click(function(){
        $('#searchType').val($(this).attr('data'));
        $('.btn-search').children('.btn').html($(this).text() + '<i class="caret"></i>')
    })
    $(document).on('click','.delGoods',function() {
        if ( confirm('确定要删移除商品吗？') ) {
            var $this = $(this);
            var id = $(this).attr('data');
            $.post('/push/del',{'id':id},function(result) {
                if ( result.success == 1 ) {
                    alert('删除成功');
                    $this.parent().parent().parent().remove();
                } else if( result.success == 0 ){
                    alert(result.error);
                }else if( result.success == 2 ){
                    alert(result.notice);
                }
            },'json')
        }
    })

    //全选
    var checkAll = false;
    $("#checkBox").click(function(){
        if(!checkAll){
            $("#table").find("tr input").prop({"checked":true});
            checkAll = true;
        }else if(checkAll) {
            checkAll = false;
            $("#table").find("tr input").prop({"checked":false});
        }
    })
</script>