
<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<div class="col-md-10 form-group">
    <h4>发货</h4>
    <hr>
    <?php if ($this->error): ?>
    <div class="alert alert-warning" role="alert"><?=$this->error?></div>
    <?php endif; ?>
      
    <form method="POST" id="form">
        <input type="hidden" name="id" value="<?=$this->oid?>">
        <div class="form-group formCustom">
    		<label class="col-md-2 control-label" style="height:50px;line-height:50px;">快递公司</label>
    		<div class="col-sm-10">
    			<div class="btn-group">
    			  <label class="checkbox">
    			     <input type="text" name="name" class="form-control">
    			  </label>    
    			 </div>
    		</div>
    	</div>
        <div class="form-group formCustom">
    		<label class="col-md-2 control-label" style="height:50px;line-height:50px;">快递单号</label>
    		<div class="col-sm-10">
    			<div class="btn-group">
    			  <label class="checkbox">
    			     <input type="text" name="number" class="form-control">
    			  </label>    
    			 </div>
    		</div>
    	</div>
  		<div class="form-group">
    	<button type="submit" class="btn btn-primary" id="submitBtn">保存添加</button>
        </div>
    </form>
</div>