<script type="text/javascript" charset="utf-8" src="/js/ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="/js/ueditor/ueditor.all.min.js"> </script>
<script type="text/javascript" charset="utf-8" src="/js/jquery.sortable.js"> </script>
<script type="text/javascript" charset="utf-8" src="/js/lightbox.js"> </script>
<link href="/css/lightbox.css" rel="stylesheet">
<div class="wrapper">
    <div id="main" class="scrollbar container-fluid">
        <div class="row mt10">
            <div class="col-xs-12">
                <div class="BreadcrumbNav white">
                    <a href="">首页</a>
                    >
                    <a href="">商家商品选货</a>
                    >
                    <a href="">编辑商品</a>
                </div>
            </div>
        </div>
        <div class="row mt10">
            <div class="col-lg-2">
                <div class="leftinfo">
                    <ul>
                        <li class="active"><div>基础信息</div></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-9 neworder-info">
                <h4 class="tit">商品信息</h4>
                <hr />
                <form method="POST" action="/shopmarket/edit" enctype="multipart/form-data" id="form">
                    <input type="hidden" name="id" value="<?=$this->Info['id']; ?>"/>
                    <?php include(dirname(__FILE__) . '/form.phtml')?>
                    <div class="form-group text-right">
                        <button type="submit" id="submitBtn" class="btn btn-primary">保存修改</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
<script type="text/javascript">
    $('#submitBtn').click(function() {
        $('#form').submit();
    })
</script>