<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0"/>
<meta name="apple-mobile-web-app-capable" content="yes"/>
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/images/splash/splash-icon.png">
<link rel="apple-touch-startup-image" href="/images/splash/splash-screen.png" 			media="screen and (max-device-width: 320px)" />  
<link rel="apple-touch-startup-image" href="/images/splash/splash-screen@2x.png" 		media="(max-device-width: 480px) and (-webkit-min-device-pixel-ratio: 2)" /> 
<link rel="apple-touch-startup-image" sizes="640x1096" href="/images/splash/splash-screen@3x.png" />
<link href="/css/style.css"     		rel="stylesheet" type="text/css">
<link href="<?php if($this->color): ?><?=$this->color ?><?php else: ?>/css/menus-background.css<?php endif; ?>" rel="stylesheet" type="text/css"  id="pagestyle">
<link href="/css/framework.css" 		rel="stylesheet" type="text/css">
<link href="/css/owl.carousel.css" 	 rel="stylesheet" type="text/css">
<link href="/css/owl.theme.css" 		rel="stylesheet" type="text/css">
<link href="/css/swipebox.css"		 rel="stylesheet" type="text/css">
<link href="/css/colorbox.css"		 rel="stylesheet" type="text/css">
<!--自定义样式-->
<link href="/css/custom.css"	rel="stylesheet" type="text/css">
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/jqueryui.js"></script>
<script type="text/javascript" src="/js/owl.carousel.min.js"></script>
<script type="text/javascript" src="/js/jquery.swipebox.js"></script>
<script type="text/javascript" src="/js/colorbox.js"></script>
<script type="text/javascript" src="/js/snap.js"></script>
<script type="text/javascript" src="/js/contact.js"></script>
<script type="text/javascript" src="/js/custom.js"></script>
<script type="text/javascript" src="/js/framework.js"></script>
<script type="text/javascript" src="/js/framework.launcher.js"></script>
<script type="text/javascript" src="/js/function.js"></script>
