<script>

//上传文件点击
$(document).on("click", "#file_a", function () {
	$("#file").trigger("click");
	return false ;
});

//上传文件post
$(document).on("change","#file",function(){
    //空对象然后添加
    var fd = new FormData();
    fd.append("file", $(":file")[0].files[0]); //jQuery 方式
    //jQuery 方式发送请求
    $.ajax({
      type:"post",
      url:"/shop/uploadheadimg",
      data: fd,
      dataType:"json",
      processData: false,
      contentType: false
    }).done(function(res){  
        var imghtml = '<a id="file_a"><img alt="店铺头像" src="'+res.data.headimgurl+'" style="width: 100px;height:100px;"></a> <input type="hidden" name="headimgurl" value="'+res.data.path+'"> ';  
        $("#addproduct").html(imghtml);
    });
    return false;
});   
</script>

<div class="row mt10">
    <div class="col-lg-2">
        <div class="leftinfo">
            <ul>
                <li class="active"><div>添加-店铺</div></li>
            </ul>
        </div>
    </div>
    <input type="hidden" name="page" value="<?=$this->page?>" />
    <input type="hidden" name="keyword" value="<?=$this->keyword?>" />
    <div class="col-lg-9 neworder-info">
        <h4 class="tit">店铺</h4>
        <hr />
        <div class="row childpad">
            <label class="col-lg-1 col-md-2 control-label">店铺名称</label>
            <div class="col-sm-4">
                <input type="text" name="name" id="name" class="form-control" value="<?=$this->info['name']?>" placeholder="店铺名称"/>
            </div>
        </div>
        <!--
        <div class="row childpad">
            <label class="col-lg-1 col-md-2 control-label">类型</label>
            <div class="col-sm-2">
                <select class="form-control" id="type" name="type">
                    <option value="1" <?php if($this->info['type'] == 1) echo "selected='selected'" ?>>供应商</option>
                    <option value="3" <?php if($this->info['type'] == 3) echo "selected='selected'" ?>>分销商</option>
                </select>
            </div>
        </div>
        -->
        <div class="row childpad">
            <label class="col-lg-1 col-md-2 control-label">分组类别</label>
            <div class="col-sm-2">
                <select class="form-control" id="category" name="category">
                    <option value="">请选择</option>
                    <option value="1" <?php if($this->info['category'] == 1) echo "selected='selected'" ?>>只有一个</option>
                    <option value="2" <?php if($this->info['category'] == 2) echo "selected='selected'" ?>>绣花张</option>
                    <option value="3" <?php if($this->info['category'] == 3) echo "selected='selected'" ?>>悦容阁</option>
                </select>
            </div>
        </div>
        <div class="row childpad">
            <label class="col-lg-1 col-md-2 control-label">负责人</label>
            <div class="col-sm-2">
                <select class="form-control" id="principal" name="principal">
                    <option value="">请选择</option>
                    <?php foreach ($this->developers as $k => $v) : ?>
                    <option value="<?=$v['id']?>" <?php if($this->info['principal'] == $v['id']) echo "selected='selected'" ?>><?=$v['name']?></option>
                    <?php endforeach;?>
                </select>
            </div>
        </div>  
        

        <div class="row childpad">
            <label class="col-lg-1 col-md-2 control-label">店主</label>
            <div class="col-sm-10" id="checkedGroup" >
                <div class="btn-group" id="checkBox">
                    <input type="checkbox">
                    全选
                </div>
                <?php foreach ($this->supplier as $v): ?>
                     <div class="btn-group check-group">
                         <input type="checkbox" name="uid[]" value="<?=$v['id'];?>" <?php if($this->info['skp']): ?> <?php if(in_array($v['id'], $this->info['skp'])) echo "checked='checked'"; ?><?php endif; ?>><?=$v['name'];?>
                     </div>
                 <?php endforeach; ?>
            </div>
        </div>
        <div class="row childpad">
            <label class="col-lg-1 col-md-2 control-label">结算周期</label>
            <div class="col-sm-4">
                <div class="input-group">
                    <input type="text" class="form-control inpwidth100" name="period" value="<?=$this->info['period'] ? $this->info['period'] : 7 ?>" />
                    <div class="input-group-addon">天</div>
                </div>
            </div>
        </div>
        <div class="row childpad">
            <label class="col-lg-1 col-md-2 control-label">包邮限额</label>
            <div class="col-sm-4">
                <input class="form-control textinput" type="text" id="quota" name="quota" value="<?=$this->info['quota'] ? $this->info['quota'] : 500 ?>" placeholder="" >
            </div>
        </div>
        <div class="row childpad">
            <label class="col-lg-1 col-md-2 control-label">平倍</label>
            <div class="col-sm-4">
                <input class="form-control textinput" type="text" id="ptimes" name="ptimes" value="<?php if($this->info['ptimes']){echo $this->info['ptimes'];}else{echo "1.15";}?>" placeholder="平倍数" >
            </div>
        </div>
        <div class="row childpad">
            <label class="col-lg-1 col-md-2 control-label">市倍</label>
            <div class="col-sm-4">
                <input class="form-control textinput" type="text" id="mtimes" name="mtimes" value="<?php if($this->info['mtimes']){echo $this->info['mtimes'];}else{echo "2.5";}?>" placeholder="市倍数" >
            </div>
        </div>
        <div class="row childpad">
            <label class="col-lg-1 col-md-2 control-label">地址</label>
            <div class="col-sm-2">
                <select name="province" id="province" class="province form-control" style="width:120px;display:inline">
                <option value="">请选择省份</option>
                <?php foreach ($this->province as $v): ?>
                    <option value="<?=$v['id'] ?>" <?php if($v['id'] == $this->info['province']) echo "selected='selected'";?>><?=$v['name'] ?></option>
                <?php endforeach; ?>
                </select>
            </div>
            <div class="col-sm-2">
                <select name="city" id="city" class="city form-control" style="width:120px;display:inline">
                    <option value="">请选择城市</option>
                    <?php if($this->city): ?>
                    <?php foreach ($this->city as $v): ?>
                        <option value="<?=$v['id'] ?>" <?php if($v['id'] == $this->info['city']) echo "selected='selected'";?> ><?=$v['name'] ?></option>
                    <?php endforeach; ?>
                    <?php endif; ?>
                </select>
            </div>
            <div class="col-sm-2">
                <select name="area" id="area" class="area form-control" style="width:120px;display:inline">
                    <option value="">请选择地区</option>
                    <?php if($this->area): ?>
                    <?php foreach ($this->area as $v): ?>
                        <option value="<?=$v['id'] ?>" <?php if($v['id'] == $this->info['area']) echo "selected='selected'";?> ><?=$v['name'] ?></option>
                    <?php endforeach; ?>
                    <?php endif; ?>
                </select>
            </div>
        </div>
        <div class="row childpad">
            <label class="col-lg-1 col-md-2 control-label">详细地址</label>
            <div class="col-sm-10">
                <input class="form-control textinput" type="text" name="address" value="<?=$this->info['address'] ?>"  placeholder="详细地址" >
            </div>
        </div>
        <div class="row childpad">
            <label class="col-lg-1 col-md-2 control-label">店铺logo</label>
            <div class="col-sm-4">
                <div class="btn-group">
                    <label class="checkbox">
                    <div id="addproduct">
                    <a id="file_a" class="btn btn-primary"><img alt="店铺头像" src="<?=$this->info['headimgurl']?>" style="width: 100px;height:100px;"></a>
                    <input name='headimgurl' type="hidden" value='<?=$this->info['hash']?>'>
                    </div>
                    <input type="file" name="file" id="file" style="display: none;"/>
                    </label>    
                </div>
            </div>
        </div>
        <div class="row childpad">
            <label class="col-lg-1 col-md-2 control-label">简介</label>
            <div class="col-sm-10">
                <textarea name="intro"></textarea>
            </div>
        </div>

    </div>
</div>
    <script type="text/javascript">
    $(document).on("change", '#province',function() {
    	var province = $(this).val();
        var city = $('#city');
        var area = $('#area');
        city.html('<option value="">请选择城市</option>');
        area.html('<option value="">请选择地区</option>');
        $.post('/shop/city',{'province':province},function(result) {
        	var html = '';
            if(result.success == 1) {
               	html += '<option value="">请选择城市</option>';
              	for(var i=0;i<result.data.length;i++){
              	    html += '<option value="'+result.data[i].id+'">'+result.data[i].name+'</option>';
              	}
            } else if( result.success == 0 ){
               html += '<option value="">请选择城市</option>';
            } else if( result.success == 2 ){
                alert(result.notice);
            }
        	city.html(html);
        },'json')
    });
    $(document).on("change", '#city',function() {
    	var city = $(this).val();
        var area = $('#area');
        area.html('<option value="">请选择地区</option>');
        $.post('/shop/area',{'city':city},function(result) {
        	var html = '';
            if(result.success == 1) {
               	html += '<option value="">请选择地区</option>';
              	for(var i=0;i<result.data.length;i++){
              	    html += '<option value="'+result.data[i].id+'">'+result.data[i].name+'</option>';
              	}
            } else if( result.success == 0 ){
               html += '<option value="">请选择地区</option>';
            } else if( result.success == 2 ){
                alert(result.notice);
            }
        	area.html(html);
        },'json')
    });
    $('#checkedGroup').find('.check-group').click(function(){
        if($(this).children('input').is(':checked')){
            $(this).children('input').prop('checked',false);
        }else {
            $(this).children('input').prop('checked',true);
        }
    })
    $('#checkedGroup').find('.check-group').children('input').click(function(e){
        e.stopPropagation();
    })
    //全选
    var checkAll = false;
    $("#checkBox").children('input').click(function(e){
        e.stopPropagation();
        if(!checkAll){
            $(this).parent().siblings().find("input").prop({"checked":true});
            checkAll = true;
        }else if(checkAll) {
            checkAll = false;
            $(this).parent().siblings().find("input").prop({"checked":false});
        }
    })
    $("#checkBox").click(function(){
        if(!checkAll){
            $(this).parent().find("input").prop({"checked":true});
            checkAll = true;
        }else if(checkAll) {
            checkAll = false;
            $(this).parent().find("input").prop({"checked":false});
        }
    })
</script>
