
<div class="wrapper">
    <div id="main" class="container-fluid">
<!-- BreadNav -->
            <div class="row mt10">
                <div class="col-xs-12">
                    <div class="BreadcrumbNav white">
                        <a href="">首页</a>
                        >
                        <a href="">采购管理</a>
                        >
                        <a href="">店铺管理</a> 
                    </div>
                </div>
            </div>
        <div class="row mt10">
<!-- search -->            
            <div class="tabhead col-xs-12">
                <form action="" method='get'>
                        <a class="top-search btn btn-primary" href='/shop/add'>添加</a>
                        <input class="form-control top-search" style="width:150px" type="text" name="keyword" value="<?=$this->keyword?>" placeholder="店铺名称" />
                        <button class="block top-search btn btn-primary" type="submit">搜索</button>
                </form>
                <div class="setwrap top-search">
                    <button id="setWindow" class="btn btn-primary">列设置</button>
                    <div class="set-window"></div>
                </div>
                <span class='linheit'>总数：<i class='red'><?=$this->total ?></i></span>
            </div>
        </div>
<!-- content-list -->
        <div class="row tablescroll">
            <table id="table" class="scrollTable">
                <thead>
                    <tr>
                        <td>ID</td>
                        <td>店铺名称</td>
                        <td>店铺编号</td>
                        <td>包邮限额</td>
                        <td>结算周期</td>
                        <td>评分</td>
                        <td>负责人</td>
                        <td>状态</td>
                        <td>操作</td>
                    </tr>
                </thead>
                <tbody>
                    <?php if($this->list):?>
			  		<?php foreach ($this->list as $row): ?>
				  		<tr class="row_<?=$row['id']?>">
				  			<td><?=$row['id']?></td>
				  			<td><?=$row['name']?></td>
				  			<td><?=$row['scode']?></td>
                            <td><?=$row['quota']?></td>
                            <td><?=$row['period']?></td>
                            <td class="score"><?=$row['score']?></td>
                            <td><?=$row['devName']?></td>
			                <td><?php if($row['status'] == 0): ?>正常<?php else: ?>关闭<?php endif; ?></td>
				  			<td>
                                <div class="order_menu menu-btn3">
                                    <a href="/shop/edit/?id=<?=$row['id']?>&page=<?=$this->page?>&keyword=<?=$this->keyword?>">
                                        <span class="btn-orderDetails btn btn-default"><img src="/img/bianji.png"><i>编辑</i></span>
                                    </a>
                                    <?php if($row['status'] == 0): ?>
                                        <a href="/shop/disable/?id=<?=$row['id']?>&page=<?=$this->page?>&keyword=<?=$this->keyword?>">
                                            <span data="<?=$row['id']?>" class="btn-orderDetails btn btn-default"><img src="/img/jinyong.png">闭店</span>
                                        </a>
                                    <?php else: ?>
                                        <a href="/shop/enable/?id=<?=$row['id']?>&page=<?=$this->page?>&keyword=<?=$this->keyword?>">
                                            <span data="<?=$row['id']?>" class="btn-orderDetails btn btn-default"><img src="/img/qiyong.png">开启</span>
                                        </a>
                                    <?php endif; ?>
                                    <div class="btn-group btn-search">
                                        <span data="<?=$row['id']?>" class="btn btn-default setScore"><img src="/img/bianji.png">评分</span>
                                    </div>
                                </div>
                                </div>
				  			</td>
				  		</tr>
			  		<?php endforeach; ?>
			  		<?php endif;?>
                </tbody>
            </table>
        </div>
<!-- page -->
        <div class="row center mb10">
            <div class="pagenav">
                <div id="Pagination" class="flickr">
                    <?=$this->pagebar;?>
                </div>
                <div class="page-count">
                    <div>
                        每页显示<span id="perpage"><?=$this->perpage?></span>条
                        <ul id="pageCountSelect">
                            <li>-- 请选择 --</li>
                            <li>25</li>
                            <li>30</li>
                            <li>35</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
<!-- page-end -->
    </div>
</div>
<!-- 弹出框框 -->
<div class="modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">请输入评分</h4>
            </div>
            <form method="post" id="shopScore">
                <input type="hidden" name="shopId" id="shopId">
                <div class="modal-body body2">
                    <div class="col-xs-6 col-xs-offset-2">
                        <div class="inp-tit text-center">原有评分</div>
                        <div class="inp-inp">
                            <div>
                                <input class="form-control" type="text" id="orgScore" value="0" disabled />
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-xs-offset-2 mt10">
                        <div class="inp-tit text-center">设置评分</div>
                        <div class="inp-inp">
                            <div>
                                <input class="form-control" type="text" id="score" name="score" />
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <div class="modal-footer">
                    <span class="btn btn-default" data-dismiss="modal">取消</span>
                    <button id="btnSubmit" type="button" class="btn btn-primary">确定</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    //全选
    var checkAll = false;
    $("#checkBox").click(function(){
        if(!checkAll){
            $("#table").find("tr input").prop({"checked":true});
            checkAll = true;
        }else if(checkAll) {
            checkAll = false;
            $("#table").find("tr input").prop({"checked":false});
        }
    })
    $('.modal').find('.close').click(function(){
        $('.modal').hide();
    })
    $('.modal').find('.btn-default').click(function(){
        $('.modal').hide();
    })
    //<a href="/shop/setScore/?id=<?=$row['id']?>">
    $('.setScore').click(function(){
        $('#shopScore').find('input').val('');
        var shopId = $(this).attr('data');
        $('#shopId').val(shopId);
        var score = '';
        $.get('/shop/getScore',{'id':shopId},function(result){
            //console.log(result);
            if( result.success == 1 ){
                score = result.data;
                $('#orgScore').val(score);
                $('.modal').show();
            }else if( result.success == 2 ){
                alert(result.notice);
            }else{
                alert(result.error);
            }
        },'json');
    })
    $('#btnSubmit').click(function(){
        var shopId = $('#shopId').val();
        var score = parseInt( $('#score').val() );
        if( isNaN( score )  ){
            alert('请输入数字');
            return false;
        }else if( score < 0 || score > 100 ){
            alert('请输入0-100的分数');
            return false;
        }
        $.post('/shop/setScore',$('#shopScore').serialize(),function(result){
            if( result.success == 1 ){
                alert(result.data);
                $('.row_'+shopId).find('.score').text(score);
                $('.modal').hide();
            }else if( result.success == 2 ){
                alert(result.notice);
            }else{
                alert(result.error);
            }
        },'json');
    })
</script>
